In [ ]:
import numpy as np
import pandas as pd

from sklearn.model_selection import (
    train_test_split,
    cross_val_score,
    GridSearchCV
)
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import (
    StandardScaler,
    MinMaxScaler,
    OneHotEncoder,
    OrdinalEncoder,
    LabelEncoder
)

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import (
    LinearRegression,
    Ridge,
    Lasso,
    ElasticNet
)
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import (
    RandomForestRegressor,
    GradientBoostingRegressor,
    AdaBoostRegressor,
    ExtraTreesRegressor
)
from sklearn.neighbors import KNeighborsRegressor

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import (
    RandomForestClassifier,
    GradientBoostingClassifier,
    AdaBoostClassifier,
    ExtraTreesClassifier
)

from sklearn.metrics import (
    r2_score,
    mean_absolute_error,
    mean_squared_error,
    accuracy_score, f1_score,
    precision_score, recall_score,
    roc_auc_score, log_loss
)

In [ ]:
df_2010 = pd.read_csv("./indeks-standar-pencemaran-udara-(ispu)-tahun-2010-komponen-data.csv")
df_2011 = pd.read_csv("./indeks-standar-pencemaran-udara-(ispu)-tahun-2011-komponen-data.csv")
df_2012 = pd.read_csv("./indeks-standar-pencemaran-udara-(ispu)-tahun-2012-komponen-data.csv")
df_2013 = pd.read_csv("./indeks-standar-pencemaran-udara-(ispu)-tahun-2013-komponen-data.csv")
df_2014 = pd.read_csv("./indeks-standar-pencemaran-udara-(ispu)-tahun-2014-komponen-data.csv")
df_2015 = pd.read_csv("./indeks-standar-pencemaran-udara-(ispu)-tahun-2015-komponen-data.csv")
df_2016 = pd.read_csv("./indeks-standar-pencemaran-udara-(ispu)-tahun-2016-komponen-data.csv")
df_2017 = pd.read_csv("./indeks-standar-pencemaran-udara-(ispu)-tahun-2017-komponen-data.csv")
df_2018 = pd.read_csv("./indeks-standar-pencemaran-udara-(ispu)-tahun-2018-komponen-data.csv")
df_2019 = pd.read_csv("./indeks-standar-pencemaran-udara-(ispu)-tahun-2019-komponen-data.csv")
df_2020 = pd.read_csv("./indeks-standar-pencemaran-udara-(ispu)-tahun-2020-komponen-data.csv")
df_2021 = pd.read_csv("./indeks-standar-pencemaran-udara-(ispu)-tahun-2021-komponen-data.csv")
df_2022 = pd.read_csv("./indeks-standar-pencemaran-udara-(ispu)-tahun-2022-komponen-data.csv")
df_2023 = pd.read_csv("./data-indeks-standar-pencemar-udara-(ispu)-di-provinsi-dki-jakarta-2023-komponen-data.csv")
df_2024 = pd.read_csv("./data-indeks-standar-pencemar-udara-(ispu)-di-provinsi-dki-jakarta-komponen-data-2024.csv")
df_2025 = pd.read_csv("./data-indeks-standar-pencemar-udara-(ispu)-di-provinsi-dki-jakarta-komponen-data-2025.csv")
df_penduduk = pd.read_csv("./data-jumlah-penduduk-provinsi-dki-jakarta-berdasarkan-kelompok-usia-dan-jenis-kelamin-tahun-2013-2021-komponen-data.csv")
df_air = pd.read_csv("./data-kualitas-air-sungai-komponen-data.csv")
df_libur = pd.read_csv("./dataset-libur-nasional-dan-weekend.csv")
df_ndvi = pd.read_csv("./indeks-ndvi-jakarta.csv")
df_cuaca_dki_1 = pd.read_csv("./cuaca-harian-dki1-bundaranhi.csv")
df_cuaca_dki_2 = pd.read_csv("./cuaca-harian-dki2-kelapagading.csv")
df_cuaca_dki_3 = pd.read_csv("./cuaca-harian-dki3-jagakarsa.csv")
df_cuaca_dki_4 = pd.read_csv("./cuaca-harian-dki4-lubangbuaya.csv")
df_cuaca_dki_5 = pd.read_csv("./cuaca-harian-dki5-kebonjeruk.csv")

# **Data ISPU 2010 - 2020**

## Merapihkan Data Lokasi SPKU Menjadi Kodenya Saja

In [ ]:
df_2010["lokasi_spku"] = df_2010["stasiun"].str.extract(r"(DKI\d)")
df_2010 = df_2010.drop(columns="stasiun")

df_2014["lokasi_spku"] = df_2014["stasiun"].str.extract(r"(DKI\d)")
df_2014 = df_2014.drop(columns="stasiun")

df_2016["lokasi_spku"] = df_2016["stasiun"].str.extract(r"(DKI\d)")
df_2016 = df_2016.drop(columns="stasiun")

df_2017["lokasi_spku"] = df_2017["stasiun"].str.extract(r"(DKI\d)")
df_2017 = df_2017.drop(columns="stasiun")

## Pengecekan Semua Nama Kolom dari Masing-Masing Tahun Sudah Benar

In [ ]:
def parse_penanggalan_1(x):
  if pd.isna(x):
    return pd.NaT
  x=str(x)
  if "-" in x:
    return pd.to_datetime(x, format="%Y-%m-%d")
  elif "/" in x:
    return pd.to_datetime(x, format="%m/%d/%Y")
  else:
    return pd.NaT

df_2013["tanggal"] = df_2013["tanggal"].apply(parse_penanggalan_1)
df_2013["tanggal"] = df_2013["tanggal"].dt.strftime("%Y-%m-%d")

def parse_penanggalan_2(x):
  if pd.isna(x):
    return pd.NaT
  x=str(x)
  if "-" in x:
    return pd.to_datetime(x, format="%Y-%m-%d")
  elif "/" in x:
    return pd.to_datetime(x, format="%d/%m/%Y")
  else:
    return pd.NaT

df_2016["tanggal"] = df_2016["tanggal"].apply(parse_penanggalan_2)
df_2016["tanggal"] = df_2016["tanggal"].dt.strftime("%Y-%m-%d")

df_2018["tanggal"] = df_2018["tanggal"].apply(parse_penanggalan_2)
df_2018["tanggal"] = df_2018["tanggal"].dt.strftime("%Y-%m-%d")

## Merge Dataset Tahun 2010 - 2020

In [ ]:
df_merged_1 = pd.concat([df_2010, df_2011, df_2012, df_2013, df_2014, df_2015, df_2016, df_2017, df_2018, df_2019, df_2020])
df_merged_1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9842 entries, 0 to 365
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   periode_data  9842 non-null   int64
 1   tanggal       9842 non-null   object
 2   pm10          9842 non-null   object
 3   so2           9842 non-null   object
 4   co            9842 non-null   object
 5   o3            9842 non-null   object
 6   no2           9842 non-null   object
 7   max           9842 non-null   object
 8   critical      8443 non-null   object
 9   categori      9842 non-null   object
 10  lokasi_spku   9842 non-null   object
dtypes: int64(1), object(10)
memory usage: 922.7+ KB

In [ ]:
df_merged_1["tanggal"] = pd.to_datetime(df_merged_1["tanggal"],errors="coerce")

num_col = ["pm10", "so2", "co", "o3", "no2"]

df_merged_1[num_col] = df_merged_1[num_col].apply(pd.to_numeric, errors="coerce")
df_merged_1["max"] = df_merged_1["max"].replace(0, np.nan)

# df_merged_1 = df_merged_1.replace(["---", "-"], np.nan)

## Fixing Data Anomali Data Merge 1

In [ ]:
df_merged_1.value_counts()

spku_valid = ["DKI1", "DKI2", "DKI3", "DKI4", "DKI5"]
mask_valid = ((~df_merged_1["lokasi_spku"].isin(spku_valid)) & (df_merged_1["critical"].astype(str) == "4"))

tmp_critical = df_merged_1.loc[mask_valid, "categori"].copy()
tmp_categori = df_merged_1.loc[mask_valid, "lokasi_spku"].copy()

df_merged_1.loc[mask_valid, ["lokasi_spku", "critical", "categori"]] = np.nan

df_merged_1.loc[mask_valid, "critical"] = tmp_critical
df_merged_1.loc[mask_valid, "categori"] = tmp_categori

In [ ]:
df_merged_1.loc[df_merged_1["lokasi_spku"].isna()].head()

,periode_data,tanggal,pm10,so2,co,o3,no2,max,critical,categori,lokasi_spku
84,202003,2020-03-02,22.0,NaN,35.0,213.0,11.0,213,O3,SANGAT TIDAK SEHAT,NaN
85,202003,2020-03-03,22.0,NaN,NaN,201.0,15.0,201,O3,SANGAT TIDAK SEHAT,NaN
86,202003,2020-03-04,54.0,NaN,39.0,152.0,13.0,152,O3,TIDAK SEHAT,NaN
87,202003,2020-03-05,59.0,NaN,32.0,206.0,5.0,206,O3,SANGAT TIDAK SEHAT,NaN
88,202003,2020-03-06,24.0,17.0,52.0,95.0,3.0,95,O3,SEDANG,NaN

In [ ]:
df_merged_1

,periode_data,tanggal,pm10,so2,co,o3,no2,max,critical,categori,lokasi_spku
0,201001,2010-01-19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TIDAK ADA DATA,DKI2
1,201001,2010-01-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TIDAK ADA DATA,DKI2
2,201001,2010-01-21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TIDAK ADA DATA,DKI2
3,201001,2010-01-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TIDAK ADA DATA,DKI2
4,201001,2010-01-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TIDAK ADA DATA,DKI2
...,...,...,...,...,...,...,...,...,...,...,...
361,202010,2020-10-27,52.0,54.0,17.0,34.0,30.0,70,PM25,SEDANG,DKI4
362,202010,2020-10-28,66.0,54.0,29.0,32.0,33.0,89,PM25,SEDANG,DKI5
363,202010,2020-10-29,57.0,55.0,15.0,35.0,26.0,87,PM25,SEDANG,DKI4
364,202010,2020-10-30,63.0,55.0,18.0,34.0,19.0,108,PM25,TIDAK SEHAT,DKI4
365,202010,2020-10-31,45.0,55.0,15.0,29.0,20.0,72,NaN,SEDANG,0

## Perbaiki Formatting Data Merge 1

In [ ]:
df_merged_1["pm25"] = np.nan
df_merged_1 = df_merged_1[["periode_data", "tanggal", "pm10", "pm25", "so2", "co", "o3", "no2", "max", "critical", "categori", "lokasi_spku"]]
df_merged_1["tanggal"] = pd.to_datetime(df_merged_1["tanggal"], errors="coerce")
df_merged_1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9842 entries, 0 to 365
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   periode_data  9842 non-null   int64
 1   tanggal       9842 non-null   datetime64[ns]
 2   pm10          8151 non-null   float64
 3   pm25          0 non-null      float64
 4   so2           8276 non-null   float64
 5   co            8299 non-null   float64
 6   o3            8179 non-null   float64
 7   no2           8239 non-null   float64
 8   max           8469 non-null   object
 9   critical      8443 non-null   object
 10  categori      9842 non-null   object
 11  lokasi_spku   9811 non-null   object
dtypes: datetime64[ns](1), float64(6), int64(1), object(4)
memory usage: 999.6+ KB

# **Data ISPU 2021 - 2025**

### 2021

In [ ]:
df_2021["lokasi_spku"] = df_2021["stasiun"].str.extract(r"(DKI\d)")
df_2021 = df_2021.drop(columns="stasiun")

df_2021.head()

,periode_data,tanggal,pm10,pm25,so2,co,o3,no2,max,critical,categori,lokasi_spku
0,202101,2021-01-22,45,NaN,21,13,40,15,45,PM10,BAIK,DKI5
1,202101,2021-01-23,80,NaN,22,44,44,22,80,PM10,SEDANG,DKI5
2,202101,2021-01-24,27,NaN,14,9,29,---,29,CO,BAIK,DKI5
3,202101,2021-01-25,55,NaN,19,29,67,13,67,CO,SEDANG,DKI5
4,202101,2021-01-26,57,NaN,21,23,36,16,57,PM10,SEDANG,DKI5

### 2022

In [ ]:
df_2022 = df_2022.rename(columns={
    "pm_10": "pm10",
    "pm_duakomalima": "pm25"
})

raw_tanggal_2022 = df_2022["tanggal"]
df_2022["tanggal"] = pd.to_datetime(raw_tanggal_2022, errors="coerce")
mask_excel = df_2022["tanggal"].isna()

df_2022.loc[mask_excel, "tanggal"] = pd.to_datetime(
    raw_tanggal_2022[mask_excel].astype(float),
    unit="D",
    origin="1899-12-30"
)

df_2022["tanggal"] = df_2022["tanggal"].dt.date
df_2022["critical"] = df_2022["critical"].replace({"PM2,5": "PM25"})

df_2022

/tmp/ipython-input-2594063371.py:7: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_2022["tanggal"] = pd.to_datetime(raw_tanggal_2022, errors="coerce")

,periode_data,tanggal,pm10,pm25,so2,co,o3,no2,max,critical,categori,lokasi_spku
0,202212,2022-12-31,54,73,56,24,23,24,73,PM25,SEDANG,DKI4
1,202212,2022-12-30,40,64,57,21,17,24,64,PM25,SEDANG,DKI4
2,202207,2022-07-06,75,129,45,25,71,26,129,PM25,TIDAK SEHAT,DKI4
3,202207,2022-07-05,66,110,47,16,61,23,110,PM25,TIDAK SEHAT,DKI4
4,202207,2022-07-04,56,78,49,11,60,13,78,PM25,SEDANG,DKI4
...,...,...,...,...,...,...,...,...,...,...,...,...
360,202207,2022-07-11,66,112,47,15,84,29,112,PM25,TIDAK SEHAT,DKI4
361,202207,2022-07-10,63,93,47,13,84,19,93,PM25,SEDANG,DKI4
362,202207,2022-07-09,61,93,48,13,107,25,107,O3,TIDAK SEHAT,DKI2
363,202207,2022-07-08,55,80,48,17,95,25,95,O3,SEDANG,DKI2
364,202207,2022-07-07,94,135,46,29,74,44,135,PM25,TIDAK SEHAT,DKI3

### 2023

In [ ]:
df_2023["lokasi_spku"] = df_2023["stasiun"].str.extract(r"(DKI\d)")
df_2023 = df_2023.drop(columns="stasiun")

df_2023 = df_2023.rename(columns={
    "pm_sepuluh": "pm10",
    "pm_duakomalima": "pm25",
    "sulfur_dioksida": "so2",
    "karbon_monoksida": "co",
    "ozon": "o3",
    "nitrogen_dioksida": "no2",
    "parameter_pencemar_kritis": "critical",
    "kategori": "categori",
})

df_2023.loc[((df_2023["critical"].isin(["1", "2", "3", "4", "5"])) & (df_2023["categori"] == "BAIK")), "critical"] = "SO2"
df_2023.loc[((df_2023["critical"].isin(["1", "2", "3", "4", "5"])) & (df_2023["categori"].isin(["TIDAK SEHAT", "SEDANG"]))), "critical"] = "PM25"
df_2023

,periode_data,tanggal,pm10,pm25,so2,co,o3,no2,max,critical,categori,lokasi_spku
0,202302,2023-02-25,35,-,13,12,31,18,35,PM10,BAIK,DKI5
1,202302,2023-02-26,23,-,14,9,32,11,32,O3,BAIK,DKI5
2,202302,2023-02-27,20,-,13,8,33,13,33,O3,BAIK,DKI5
3,202302,2023-02-28,30,-,21,11,28,18,30,PM10,BAIK,DKI5
4,202303,2023-03-01,38,44,50,8,19,27,50,SO2,BAIK,DKI1
...,...,...,...,...,...,...,...,...,...,...,...,...
1820,202311,2023-11-26,48,71,33,21,44,20,71,PM25,SEDANG,DKI5
1821,202311,2023-11-27,51,76,32,18,53,19,76,PM25,SEDANG,DKI5
1822,202311,2023-11-28,56,88,33,20,48,21,88,PM25,SEDANG,DKI5
1823,202311,2023-11-29,56,88,32,18,56,18,88,PM25,SEDANG,DKI5
1824,202311,2023-11-30,30,57,32,15,61,17,61,O3,SEDANG,DKI5

### 2024

In [ ]:
df_2024["tahun"] = df_2024["periode_data"].astype(str).str[:4]
df_2024["tmp_tanggal"] = df_2024["tahun"] + "-" + df_2024["bulan"].astype(str) + "-" + df_2024["tanggal"].astype(str)

df_2024 = df_2024.drop(columns=["bulan", "tanggal", "tahun"])

df_2024 = df_2024.rename(columns={
    "pm_sepuluh": "pm10",
    "pm_duakomalima": "pm25",
    "sulfur_dioksida": "so2",
    "karbon_monoksida": "co",
    "ozon": "o3",
    "nitrogen_dioksida": "no2",
    "parameter_pencemar_kritis": "critical",
    "kategori": "categori",
    "tmp_tanggal": "tanggal"
})

df_2024["lokasi_spku"] = df_2024["stasiun"].str.extract(r"(DKI\d)")
df_2024 = df_2024.drop(columns="stasiun")

df_2024 = df_2024[["periode_data", "tanggal", "pm10", "pm25", "so2", "co", "o3", "no2", "max", "critical", "categori", "lokasi_spku"]]
df_2024["tanggal"] = pd.to_datetime(df_2024["tanggal"], errors="coerce")

df_2024

,periode_data,tanggal,pm10,pm25,so2,co,o3,no2,max,critical,categori,lokasi_spku
0,202401,2024-01-21,51.0,65.0,45.0,9.0,8.0,79.0,79.0,NaN,SEDANG,DKI3
1,202401,2024-01-22,27.0,34.0,45.0,5.0,8.0,56.0,56.0,NaN,SEDANG,DKI3
2,202401,2024-01-23,NaN,52.0,46.0,6.0,9.0,51.0,52.0,PM25,SEDANG,DKI3
3,202401,2024-01-24,46.0,65.0,46.0,8.0,9.0,38.0,65.0,PM25,SEDANG,DKI3
4,202401,2024-01-25,37.0,55.0,47.0,7.0,11.0,28.0,55.0,PM25,SEDANG,DKI3
...,...,...,...,...,...,...,...,...,...,...,...,...
1825,202412,2024-12-27,NaN,55.0,27.0,9.0,30.0,12.0,55.0,PM25,SEDANG,DKI5
1826,202412,2024-12-28,NaN,40.0,26.0,6.0,30.0,12.0,40.0,PM25,BAIK,DKI5
1827,202412,2024-12-29,NaN,51.0,32.0,8.0,28.0,11.0,51.0,PM25,SEDANG,DKI5
1828,202412,2024-12-30,NaN,34.0,9.0,5.0,38.0,8.0,38.0,O3,BAIK,DKI5
1829,202412,2024-12-31,NaN,26.0,9.0,3.0,26.0,3.0,26.0,PM25,BAIK,DKI5

### 2025

In [ ]:
df_2025["tahun"] = df_2025["periode_data"].astype(str).str[:4]
df_2025["tmp_tanggal"] = df_2025["tahun"] + "-" + df_2025["bulan"].astype(str) + "-" + df_2025["tanggal"].astype(str)

df_2025 = df_2025.drop(columns=["bulan", "tanggal", "tahun"])

df_2025 = df_2025.rename(columns={
    "pm_sepuluh": "pm10",
    "pm_duakomalima": "pm25",
    "sulfur_dioksida": "so2",
    "karbon_monoksida": "co",
    "ozon": "o3",
    "nitrogen_dioksida": "no2",
    "parameter_pencemar_kritis": "critical",
    "kategori": "categori",
    "tmp_tanggal": "tanggal"
})

df_2025["lokasi_spku"] = df_2025["stasiun"].str.extract(r"(DKI\d)")
df_2025 = df_2025.drop(columns="stasiun")

df_2025 = df_2025[["periode_data", "tanggal", "pm10", "pm25", "so2", "co", "o3", "no2", "max", "critical", "categori", "lokasi_spku"]]
df_2025["tanggal"] = pd.to_datetime(df_2025["tanggal"], errors="coerce")

df_2025

,periode_data,tanggal,pm10,pm25,so2,co,o3,no2,max,critical,categori,lokasi_spku
0,202504,2025-04-24,16.0,50.0,18.0,3.0,16.0,4.0,50.0,PM25,BAIK,DKI5
1,202504,2025-04-25,23.0,81.0,19.0,9.0,24.0,3.0,81.0,PM25,SEDANG,DKI5
2,202504,2025-04-26,30.0,77.0,20.0,11.0,29.0,3.0,77.0,PM25,SEDANG,DKI5
3,202504,2025-04-27,31.0,85.0,21.0,12.0,47.0,4.0,85.0,PM25,SEDANG,DKI5
4,202504,2025-04-28,24.0,78.0,20.0,9.0,37.0,4.0,78.0,PM25,SEDANG,DKI5
...,...,...,...,...,...,...,...,...,...,...,...,...
1210,202508,2025-08-31,28.0,60.0,53.0,8.0,19.0,39.0,60.0,PM25,SEDANG,DKI3
1211,202508,2025-08-01,63.0,89.0,30.0,7.0,28.0,16.0,89.0,PM25,SEDANG,DKI4
1212,202508,2025-08-02,73.0,105.0,31.0,11.0,25.0,21.0,105.0,PM25,TIDAK SEHAT,DKI4
1213,202508,2025-08-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TIDAK ADA DATA,DKI4
1214,202508,2025-08-04,63.0,84.0,27.0,14.0,26.0,26.0,84.0,PM25,SEDANG,DKI4

## Data Merge 2

In [ ]:
df_merged_2 = pd.concat([df_2021, df_2022, df_2023, df_2024, df_2025])

num_col = ["pm10", "so2", "co", "o3", "no2", "pm25"]

df_merged_2[num_col] = df_merged_2[num_col].apply(pd.to_numeric, errors="coerce")
df_merged_2["max"] = df_merged_2["max"].replace(0, np.nan)

df_merged_2["tanggal"] = pd.to_datetime(df_merged_2["tanggal"], errors="coerce")
df_merged_2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7060 entries, 0 to 1214
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   periode_data  7060 non-null   int64
 1   tanggal       7060 non-null   datetime64[ns]
 2   pm10          6584 non-null   float64
 3   pm25          6612 non-null   float64
 4   so2           6854 non-null   float64
 5   co            6936 non-null   float64
 6   o3            6920 non-null   float64
 7   no2           6893 non-null   float64
 8   max           7042 non-null   object
 9   critical      6968 non-null   object
 10  categori      7059 non-null   object
 11  lokasi_spku   7060 non-null   object
dtypes: datetime64[ns](1), float64(6), int64(1), object(4)
memory usage: 717.0+ KB

# **Dataset ISPU Dari Semua Tahun**

In [ ]:
df_ispu = pd.concat([df_merged_1, df_merged_2])
df_ispu.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16902 entries, 0 to 1214
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   periode_data  16902 non-null  int64
 1   tanggal       16902 non-null  datetime64[ns]
 2   pm10          14735 non-null  float64
 3   pm25          6612 non-null   float64
 4   so2           15130 non-null  float64
 5   co            15235 non-null  float64
 6   o3            15099 non-null  float64
 7   no2           15132 non-null  float64
 8   max           15511 non-null  object
 9   critical      15411 non-null  object
 10  categori      16901 non-null  object
 11  lokasi_spku   16871 non-null  object
dtypes: datetime64[ns](1), float64(6), int64(1), object(4)
memory usage: 1.7+ MB

### Pengecekan

In [ ]:
# 2010 - 2025 data check
x = df_ispu["tanggal"].dt.year == 2017
df_ispu[x].head(10)

,periode_data,tanggal,pm10,pm25,so2,co,o3,no2,max,critical,categori,lokasi_spku
0,201701,2017-01-27,5.0,NaN,11.0,29.0,37.0,14.0,37,O3,BAIK,DKI5
1,201701,2017-01-28,5.0,NaN,11.0,28.0,42.0,6.0,42,O3,BAIK,DKI5
2,201701,2017-01-29,6.0,NaN,11.0,29.0,26.0,13.0,29,CO,BAIK,DKI5
3,201701,2017-01-30,7.0,NaN,11.0,28.0,41.0,5.0,41,O3,BAIK,DKI5
4,201701,2017-01-31,6.0,NaN,11.0,26.0,42.0,7.0,42,O3,BAIK,DKI5
5,201702,2017-02-01,41.0,NaN,16.0,22.0,27.0,3.0,41,PM10,BAIK,DKI1
6,201702,2017-02-02,49.0,NaN,NaN,23.0,41.0,3.0,49,PM10,BAIK,DKI1
7,201702,2017-02-03,53.0,NaN,NaN,28.0,34.0,3.0,53,PM10,SEDANG,DKI1
8,201702,2017-02-04,30.0,NaN,NaN,17.0,35.0,2.0,35,O3,BAIK,DKI1
9,201702,2017-02-05,22.0,NaN,NaN,15.0,37.0,2.0,37,O3,BAIK,DKI1

### Mapping hanya 3 kategori

In [ ]:
df_ispu.info()
df_ispu['categori'].value_counts()

mapping = {
    "BERBAHAYA": "TIDAK SEHAT",
    "SANGAT TIDAK SEHAT": "TIDAK SEHAT"
}

# apply mapping
df_ispu["categori"] = df_ispu["categori"].replace(mapping)

# cek distribusi terbaru
print(df_ispu["categori"].value_counts())

<class 'pandas.core.frame.DataFrame'>
Index: 16902 entries, 0 to 1214
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   periode_data  16902 non-null  int64
 1   tanggal       16902 non-null  datetime64[ns]
 2   pm10          14735 non-null  float64
 3   pm25          6612 non-null   float64
 4   so2           15130 non-null  float64
 5   co            15235 non-null  float64
 6   o3            15099 non-null  float64
 7   no2           15132 non-null  float64
 8   max           15511 non-null  object
 9   critical      15411 non-null  object
 10  categori      16901 non-null  object
 11  lokasi_spku   16871 non-null  object
dtypes: datetime64[ns](1), float64(6), int64(1), object(4)
memory usage: 1.7+ MB
categori
SEDANG            10468
TIDAK SEHAT        2631
BAIK               2344
TIDAK ADA DATA     1458
Name: count, dtype: int64

In [ ]:
df_clean = df_ispu.copy()

df_clean = df_clean[df_clean["categori"] != "TIDAK ADA DATA"].reset_index(drop=True)

df_clean["categori"].value_counts()

categori
SEDANG         10468
TIDAK SEHAT     2631
BAIK            2344
Name: count, dtype: int64

In [ ]:
from sklearn.utils import resample

df_sedang = df_clean[df_clean["categori"] == "SEDANG"]
df_baik   = df_clean[df_clean["categori"] == "BAIK"]
df_tidak  = df_clean[df_clean["categori"] == "TIDAK SEHAT"]

n_target = 5000
# atau kalau mau mengikuti kelas mayor kedua:
# n_target = len(df_tidak)

df_sedang_under = resample(
    df_sedang,
    replace=False,
    n_samples=n_target,
    random_state=42
)

df_balanced = pd.concat(
    [df_sedang_under, df_baik, df_tidak],
    ignore_index=True
)

df_balanced = df_balanced.sample(
    frac=1,
    random_state=42
).reset_index(drop=True)

df_balanced["categori"].value_counts()

categori
SEDANG         5000
TIDAK SEHAT    2631
BAIK           2344
Name: count, dtype: int64

In [ ]:
df_balanced = df_balanced.drop(columns='pm25')
df_balanced.isna().sum()

periode_data      0
tanggal           0
pm10            516
so2             207
co              152
o3              242
no2             222
max               0
critical         28
categori          0
lokasi_spku      24
dtype: int64

In [ ]:
df_balanced = df_balanced.dropna()
df_balanced.isna().sum()

periode_data    0
tanggal         0
pm10            0
so2             0
co              0
o3              0
no2             0
max             0
critical        0
categori        0
lokasi_spku     0
dtype: int64

### Handle Missing value

In [ ]:
# # ganti tanda tanda - / -- / kosong ke NaN
# null_chars = ['-', '--', '---', '', ' ', 'null', 'NULL', 'NaN']
# df_balanced = df_balanced.replace(null_chars, np.nan)

# df_balanced["tanggal"] = pd.to_datetime(df_balanced["tanggal"])
# df_balanced = df_balanced.sort_values(["lokasi_spku", "tanggal"])

# # set tanggal sebagai index
# df_balanced = df_balanced.set_index("tanggal")

# pollutants_interp = ["pm10", "so2", "co", "o3", "no2"]

# # interpolasi waktu per stasiun (AMAN)
# df_balanced[pollutants_interp] = (
#     df_balanced
#     .groupby("lokasi_spku")[pollutants_interp]
#     .transform(lambda x: x.interpolate(method="time"))
# )

# # rapikan sisa NaN di awal / akhir segmen
# df_balanced[pollutants_interp] = (
#     df_balanced
#     .groupby("lokasi_spku")[pollutants_interp]
#     .ffill()
#     .bfill()
# )

# df_balanced = df_balanced.reset_index()

# df_balanced = df_balanced.dropna(subset=["pm10", "so2", "co", "o3", "no2"])
# df_balanced = df_balanced.dropna(subset=["categori"])
# df_balanced = df_balanced.dropna(subset=["lokasi_spku"])

# df_balanced.isna().sum()

### Pseudolabeling

In [ ]:
# from xgboost import XGBClassifier

# df = df_ispu.copy()
# df = df.drop(columns=["max", "critical"], errors="ignore")

# df = df_ispu.drop(columns=["pm25"], errors="ignore")

# features = ["pm10", "so2", "co", "o3", "no2"]

# df_labeled = df[df["categori"] != "TIDAK ADA DATA"].copy()
# df_unlabeled = df[df["categori"] == "TIDAK ADA DATA"].copy()

# le = LabelEncoder()
# y_train = le.fit_transform(df_labeled["categori"])

# X_train = df_labeled[features]
# X_unlabeled = df_unlabeled[features]

# from sklearn.ensemble import RandomForestClassifier

# model = GradientBoostingClassifier(random_state=42)

# model.fit(X_train, y_train)

# pseudo_pred = model.predict(X_unlabeled)
# pseudo_label = le.inverse_transform(pseudo_pred)

# df_unlabeled["categori"] = pseudo_label
# df_unlabeled["label_source"] = "pseudo"

# df_labeled["label_source"] = "original"

# df_ispu_pseudo = pd.concat([df_labeled, df_unlabeled], axis=0)

# df_ispu_pseudo["max"] = df_ispu_pseudo[features].max(axis=1)
# df_ispu_pseudo["critical"] = df_ispu_pseudo[features].idxmax(axis=1)
# df_ispu_pseudo["critical"] = df_ispu_pseudo['critical'].str.upper()

In [ ]:
df_ispu_pseudo = df_balanced.copy()
df_ispu_pseudo['categori'].value_counts()

categori
SEDANG         4499
TIDAK SEHAT    2409
BAIK           1900
Name: count, dtype: int64

In [ ]:
df_ispu_pseudo.head()

,periode_data,tanggal,pm10,so2,co,o3,no2,max,critical,categori,lokasi_spku
0,201605,2016-05-15,50.0,16.0,14.0,38.0,5.0,50,PM10,BAIK,DKI4
1,201012,2010-12-22,45.0,4.0,6.0,32.0,3.0,45,PM10,BAIK,DKI3
2,201701,2017-01-29,6.0,11.0,29.0,26.0,13.0,29,CO,BAIK,DKI5
3,201509,2015-09-16,76.0,31.0,23.0,71.0,17.0,76,PM10,SEDANG,DKI4
4,201003,2010-03-15,52.0,8.0,28.0,30.0,15.0,52,PM10,SEDANG,DKI1

### Feature Engineering

In [ ]:
df_ispu_pseudo['tanggal'] = pd.to_datetime(df_ispu_pseudo['tanggal'])
df_libur['tanggal'] = pd.to_datetime(df_libur['tanggal'])

df = df_ispu_pseudo.merge(
    df_libur[['tanggal', 'is_holiday_nasional', 'is_weekend', 'day_name']],
    on='tanggal',
    how='left'
)

# Hari, bulan, tahun
df['day'] = df['tanggal'].dt.day
df['month'] = df['tanggal'].dt.month
df['year'] = df['tanggal'].dt.year
df['day_of_week'] = df['tanggal'].dt.dayofweek  # Senin=0, Minggu=6

# Sin / cos bulanan untuk musiman tahunan
df['sin_month'] = np.sin(2 * np.pi * df['month']/12)
df['cos_month'] = np.cos(2 * np.pi * df['month']/12)

# Sin / cos mingguan untuk pola mingguan
df['sin_week'] = np.sin(2 * np.pi * df['day_of_week']/7)
df['cos_week'] = np.cos(2 * np.pi * df['day_of_week']/7)

df = df.sort_values(["lokasi_spku", "tanggal"])

lag_days = [1, 7, 30]
rolling_days = [7, 30]

for col in ['pm10','so2','co','o3','no2']:

    for lag in lag_days:
        df[f'{col}_lag{lag}'] = (
            df.groupby("lokasi_spku")[col]
              .shift(lag)
        )

    for window in rolling_days:
        g = df.groupby("lokasi_spku")[col]

        df[f'{col}_roll{window}_mean'] = (
            g.rolling(window).mean()
             .reset_index(level=0, drop=True)
        )

        df[f'{col}_roll{window}_max'] = (
            g.rolling(window).max()
             .reset_index(level=0, drop=True)
        )

        df[f'{col}_roll{window}_std'] = (
            g.rolling(window).std()
             .reset_index(level=0, drop=True)
        )

df['pm10_so2_ratio'] = df['pm10'] / (df['so2'] + 1e-6)  # +epsilon supaya tidak dibagi nol
df['co_o3_ratio'] = df['co'] / (df['o3'] + 1e-6)

df = df.dropna()

df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
Index: 8658 entries, 2507 to 1285
Data columns (total 69 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   periode_data         8658 non-null   int64
 1   tanggal              8658 non-null   datetime64[ns]
 2   pm10                 8658 non-null   float64
 3   so2                  8658 non-null   float64
 4   co                   8658 non-null   float64
 5   o3                   8658 non-null   float64
 6   no2                  8658 non-null   float64
 7   max                  8658 non-null   object
 8   critical             8658 non-null   object
 9   categori             8658 non-null   object
 10  lokasi_spku          8658 non-null   object
 11  is_holiday_nasional  8658 non-null   int64
 12  is_weekend           8658 non-null   int64
 13  day_name             8658 non-null   object
 14  day                  8658 non-null   int32
 15  month                8658 non-null   int32
 16  year                 8658 non-null   int32
 17  day_of_week          8658 non-null   int32
 18  sin_month            8658 non-null   float64
 19  cos_month            8658 non-null   float64
 20  sin_week             8658 non-null   float64
 21  cos_week             8658 non-null   float64
 22  pm10_lag1            8658 non-null   float64
 23  pm10_lag7            8658 non-null   float64
 24  pm10_lag30           8658 non-null   float64
 25  pm10_roll7_mean      8658 non-null   float64
 26  pm10_roll7_max       8658 non-null   float64
 27  pm10_roll7_std       8658 non-null   float64
 28  pm10_roll30_mean     8658 non-null   float64
 29  pm10_roll30_max      8658 non-null   float64
 30  pm10_roll30_std      8658 non-null   float64
 31  so2_lag1             8658 non-null   float64
 32  so2_lag7             8658 non-null   float64
 33  so2_lag30            8658 non-null   float64
 34  so2_roll7_mean       8658 non-null   float64
 35  so2_roll7_max        8658 non-null   float64
 36  so2_roll7_std        8658 non-null   float64
 37  so2_roll30_mean      8658 non-null   float64
 38  so2_roll30_max       8658 non-null   float64
 39  so2_roll30_std       8658 non-null   float64
 40  co_lag1              8658 non-null   float64
 41  co_lag7              8658 non-null   float64
 42  co_lag30             8658 non-null   float64
 43  co_roll7_mean        8658 non-null   float64
 44  co_roll7_max         8658 non-null   float64
 45  co_roll7_std         8658 non-null   float64
 46  co_roll30_mean       8658 non-null   float64
 47  co_roll30_max        8658 non-null   float64
 48  co_roll30_std        8658 non-null   float64
 49  o3_lag1              8658 non-null   float64
 50  o3_lag7              8658 non-null   float64
 51  o3_lag30             8658 non-null   float64
 52  o3_roll7_mean        8658 non-null   float64
 53  o3_roll7_max         8658 non-null   float64
 54  o3_roll7_std         8658 non-null   float64
 55  o3_roll30_mean       8658 non-null   float64
 56  o3_roll30_max        8658 non-null   float64
 57  o3_roll30_std        8658 non-null   float64
 58  no2_lag1             8658 non-null   float64
 59  no2_lag7             8658 non-null   float64
 60  no2_lag30            8658 non-null   float64
 61  no2_roll7_mean       8658 non-null   float64
 62  no2_roll7_max        8658 non-null   float64
 63  no2_roll7_std        8658 non-null   float64
 64  no2_roll30_mean      8658 non-null   float64
 65  no2_roll30_max       8658 non-null   float64
 66  no2_roll30_std       8658 non-null   float64
 67  pm10_so2_ratio       8658 non-null   float64
 68  co_o3_ratio          8658 non-null   float64
dtypes: datetime64[ns](1), float64(56), int32(4), int64(3), object(5)
memory usage: 4.5+ MB

,periode_data,tanggal,pm10,so2,co,o3,no2,max,critical,categori,...,no2_lag7,no2_lag30,no2_roll7_mean,no2_roll7_max,no2_roll7_std,no2_roll30_mean,no2_roll30_max,no2_roll30_std,pm10_so2_ratio,co_o3_ratio
2507,201002,2010-02-06,65.0,8.0,59.0,24.0,15.0,65,PM10,SEDANG,...,17.0,14.0,13.714286,23.0,4.386125,13.800000,24.0,4.229616,8.124999,2.458333
5619,201002,2010-02-08,46.0,5.0,31.0,42.0,17.0,46,PM10,BAIK,...,11.0,9.0,14.571429,23.0,4.353433,14.066667,24.0,4.168299,9.199998,0.738095
6070,201002,2010-02-10,50.0,8.0,31.0,39.0,14.0,50,PM10,BAIK,...,12.0,9.0,14.857143,23.0,4.220133,14.233333,24.0,4.057206,6.249999,0.794872
4182,201002,2010-02-11,47.0,5.0,27.0,26.0,14.0,47,PM10,BAIK,...,10.0,6.0,15.428571,23.0,3.690399,14.500000,24.0,3.748563,9.399998,1.038461
7477,201002,2010-02-14,55.0,6.0,61.0,16.0,13.0,61,CO,SEDANG,...,13.0,8.0,15.428571,23.0,3.690399,14.666667,24.0,3.555795,9.166665,3.812500

### Training Clf Model

In [ ]:
!pip install -q catboost xgboost

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.2/99.2 MB 8.7 MB/s eta 0:00:00

In [ ]:
split_date = '2024-01-01'

# df = df.drop(columns="label_source")

df_train = df[df['tanggal'] < split_date]
df_val   = df[df['tanggal'] >= split_date]

In [ ]:
from sklearn.neural_network import MLPClassifier
from catboost import CatBoostClassifier
from xgboost import XGBClassifier
from sklearn.impute import SimpleImputer
target = 'categori'
drop_cols = [
    target,        # label
    "tanggal",         # index waktu
    "periode_data", # info waktu mentah
    "critical",     # turunan ISPU
    "max"           # dipakai menentukan kategori
]

cat_features = ["lokasi_spku", 'day_name']
num_features = [
    c for c in df.columns
    if c not in drop_cols + cat_features and df[c].dtype in [np.float64, np.int64]
]


X_train = df_train[cat_features + num_features]
y_train = df_train[target]

X_val = df_val[cat_features + num_features]
y_val = df_val[target]

# Create a numeric transformer with imputation
numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', StandardScaler()) # Optional: add scaling as well
])

preprocess = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore'), ['lokasi_spku']),
        ('num', numeric_transformer, num_features) # Use the numeric_transformer here
    ]
)

cpu_models = {
    # ===== Linear =====
    "Logistic Regression": LogisticRegression(max_iter=1000),

    # ===== Distance =====
    "KNN": KNeighborsClassifier(n_neighbors=5),

    # ===== Tree =====
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "Random Forest": RandomForestClassifier(
        n_estimators=300,
        random_state=42),

    # ===== Boosting =====
    "Gradient Boosting": GradientBoostingClassifier(random_state=42)
}

results = []

for name, model in cpu_models.items():
    pipe = Pipeline([
        ('prep', preprocess),
        ('model', model)
    ])

    pipe.fit(X_train, y_train)
    y_pred = pipe.predict(X_val)

    f1 = f1_score(y_val, y_pred, average='weighted')

    results.append({
        'model': name,
        'f1_score': f1
    })

X_train_cb = df_train.drop(columns=drop_cols)
y_train_cb = df_train[target]

X_val_cb = df_val.drop(columns=drop_cols)
y_val_cb = df_val[target]

cat_features_cb = ['lokasi_spku', 'day_name']

cat_model = CatBoostClassifier(
    iterations=800,
    learning_rate=0.05,
    depth=8,
    loss_function="MultiClass",
    eval_metric="MultiClass",
    task_type="CPU",
    auto_class_weights="Balanced",
    random_seed=42,
    verbose=200
)

cat_model.fit(
    X_train_cb,
    y_train_cb,
    cat_features=cat_features_cb,
    eval_set=(X_val_cb, y_val_cb),
    use_best_model=True
)

y_pred_cb = cat_model.predict(X_val_cb)

results.append({
    'model': 'CatBoost (GPU)',
    'f1_score': f1_score(y_val_cb, y_pred_cb, average='weighted')
})

le = LabelEncoder()
y_train_enc = le.fit_transform(y_train)
y_val_enc = le.transform(y_val)

X_train_xgb = preprocess.fit_transform(X_train)
X_val_xgb = preprocess.transform(X_val)

xgb_model = XGBClassifier(
    n_estimators=600,
    learning_rate=0.05,
    max_depth=8,
    subsample=0.8,
    colsample_bytree=0.8,
    objective="multi:softprob",
    eval_metric="mlogloss",
    tree_method="hist",
    predictor="cpu_predictor",
    random_state=42
)

xgb_model.fit(X_train_xgb, y_train_enc)

y_pred_xgb = xgb_model.predict(X_val_xgb)

results.append({
    'model': 'XGBoost (GPU)',
    'f1_score': f1_score(y_val_enc, y_pred_xgb, average='weighted')
})

df_results = (
    pd.DataFrame(results)
    .sort_values('f1_score', ascending=False)
    .reset_index(drop=True)
)

df_results

0:	learn: 1.0263838	test: 1.0641775	best: 1.0641775 (0)	total: 152ms	remaining: 2m 1s
200:	learn: 0.0857206	test: 0.6470956	best: 0.6289152 (80)	total: 21.8s	remaining: 1m 5s
400:	learn: 0.0571482	test: 0.6694567	best: 0.6289152 (80)	total: 43.8s	remaining: 43.6s
600:	learn: 0.0419081	test: 0.6930809	best: 0.6289152 (80)	total: 1m 6s	remaining: 22.1s
799:	learn: 0.0323844	test: 0.7168915	best: 0.6289152 (80)	total: 1m 27s	remaining: 0us

bestTest = 0.6289152433
bestIteration = 80

Shrink model to first 81 iterations.

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [06:40:26] WARNING: /workspace/src/learner.cc:790:
Parameters: { "predictor" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

                 model  f1_score
0        XGBoost (GPU)  0.740256
1    Gradient Boosting  0.731122
2       CatBoost (GPU)  0.730387
3        Random Forest  0.701422
4        Decision Tree  0.658675
5  Logistic Regression  0.639469
6                  KNN  0.598742

#### Hyperparameter Tuning Model XGBoost

In [ ]:
!pip install optuna -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 413.9/413.9 kB 9.5 MB/s eta 0:00:00

In [ ]:
import optuna
import xgboost as xgb
from sklearn.ensemble import GradientBoostingClassifier, VotingClassifier
from sklearn.model_selection import TimeSeriesSplit, cross_val_score, GridSearchCV
from sklearn.preprocessing import OrdinalEncoder
from sklearn.metrics import f1_score
from sklearn.base import clone

In [ ]:
# Suppress warnings agar output bersih
import warnings
warnings.filterwarnings('ignore')

# --- 1. PREPROCESSING (Encoding) ---
# Kita ubah semua kolom object menjadi angka agar aman masuk ke semua model
# Asumsi: X_train, X_val, y_train, y_val sudah ada dari split sebelumnya

# Buat copy agar data asli aman
X_train_enc = X_train.copy()
X_val_enc = X_val.copy()

# Cari kolom kategorikal
cat_cols = X_train_enc.select_dtypes(include=['object']).columns.tolist()
print(f"Meng-encode kolom: {cat_cols}")

# Encode
encoder = OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1)
X_train_enc[cat_cols] = encoder.fit_transform(X_train[cat_cols])
X_val_enc[cat_cols] = encoder.transform(X_val[cat_cols])

# Siapkan TimeSeriesSplit untuk validasi (Mencegah Data Leakage)
tscv = TimeSeriesSplit(n_splits=3)

Meng-encode kolom: ['lokasi_spku', 'day_name']

In [ ]:
from sklearn.preprocessing import LabelEncoder

# --- 1. BERSIHKAN DATA TARGET (Hapus 'O3') ---
# Cek apakah ada 'O3' di y_train atau y_val dan hapus baris terkait di X dan y
def clean_garbage_labels(X, y):
    # Cari index yang labelnya BUKAN kategori valid (misal 'O3' atau garbage lainnya)
    valid_categories = ['BAIK', 'SEDANG', 'TIDAK SEHAT']
    mask = y.isin(valid_categories)

    print(f"Data awal: {len(y)}")
    X_clean = X[mask].copy()
    y_clean = y[mask].copy()
    print(f"Data setelah cleaning: {len(y_clean)} (Dibuang {len(y) - len(y_clean)} baris sampah)")

    return X_clean, y_clean

# Terapkan pembersihan (Asumsi X_train_enc sudah ada dari langkah sebelumnya)
X_train_clean, y_train_clean = clean_garbage_labels(X_train_enc, y_train)
X_val_clean, y_val_clean = clean_garbage_labels(X_val_enc, y_val)

# --- 2. ENCODE TARGET (String -> Angka) ---
# XGBoost Wajib pakai angka 0, 1, 2...
le = LabelEncoder()
y_train_final = le.fit_transform(y_train_clean)
y_val_final = le.transform(y_val_clean)

print("Kelas yang dikenali:", le.classes_)
# Output harusnya cuma 5 kelas ISPU, tidak ada 'O3' lagi.

# --- 3. UPDATE FUNGSI OPTUNA ---
# Pastikan menggunakan y_train_final (yang sudah angka)

def tune_xgboost(trial):
    params = {
        'objective': 'multi:softmax',
        'num_class': len(le.classes_), # Gunakan panjang kelas dari LabelEncoder
        'tree_method': 'hist',
        'verbosity': 0,
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3),
        'max_depth': trial.suggest_int('max_depth', 3, 10),
        'subsample': trial.suggest_float('subsample', 0.6, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.6, 1.0),
        'n_estimators': trial.suggest_int('n_estimators', 100, 500), # Kurangi sedikit biar cepat
        'reg_alpha': trial.suggest_float('reg_alpha', 0, 10),
        'reg_lambda': trial.suggest_float('reg_lambda', 0, 10)
    }

    model = xgb.XGBClassifier(**params)

    # PENTING: Gunakan X_train_clean dan y_train_final
    scores = cross_val_score(model, X_train_clean, y_train_final, cv=tscv, scoring='f1_macro')
    return scores.mean()

# Update juga fungsi lainnya untuk menggunakan y_train_final!

# --- JALANKAN ULANG OPTUNA ---
print("Mulai Tuning Ulang...")
study_xgb = optuna.create_study(direction='maximize')
study_xgb.optimize(tune_xgboost, n_trials=20)

[I 2026-02-05 06:40:48,466] A new study created in memory with name: no-name-681ae2de-98a6-4bd6-98c3-6f2ec2914694

Data awal: 7022
Data setelah cleaning: 7022 (Dibuang 0 baris sampah)
Data awal: 1636
Data setelah cleaning: 1636 (Dibuang 0 baris sampah)
Kelas yang dikenali: ['BAIK' 'SEDANG' 'TIDAK SEHAT']
Mulai Tuning Ulang...

[I 2026-02-05 06:41:15,410] Trial 0 finished with value: 0.901109962315029 and parameters: {'learning_rate': 0.04474452623916002, 'max_depth': 5, 'subsample': 0.6069513591486416, 'colsample_bytree': 0.8922240733428632, 'n_estimators': 376, 'reg_alpha': 8.792373064644433, 'reg_lambda': 2.3055968886747324}. Best is trial 0 with value: 0.901109962315029.
[I 2026-02-05 06:41:27,339] Trial 1 finished with value: 0.8952017343270335 and parameters: {'learning_rate': 0.019778756116264597, 'max_depth': 7, 'subsample': 0.6605393199473498, 'colsample_bytree': 0.7114455714960313, 'n_estimators': 325, 'reg_alpha': 3.8920925285163097, 'reg_lambda': 1.0923890397414382}. Best is trial 0 with value: 0.901109962315029.
[I 2026-02-05 06:41:30,238] Trial 2 finished with value: 0.9017388385448141 and parameters: {'learning_rate': 0.2369863091115691, 'max_depth': 8, 'subsample': 0.647696223728336, 'colsample_bytree': 0.852290113701754, 'n_estimators': 182, 'reg_alpha': 7.191798524329556, 'reg_lambda': 4.912631012283732}. Best is trial 2 with value: 0.9017388385448141.
[I 2026-02-05 06:41:35,070] Trial 3 finished with value: 0.9013202598101219 and parameters: {'learning_rate': 0.23010023875260974, 'max_depth': 10, 'subsample': 0.8534069810863358, 'colsample_bytree': 0.9024210205646731, 'n_estimators': 190, 'reg_alpha': 6.023161407081751, 'reg_lambda': 6.860474204048459}. Best is trial 2 with value: 0.9017388385448141.
[I 2026-02-05 06:41:38,884] Trial 4 finished with value: 0.9022047369100684 and parameters: {'learning_rate': 0.21941954044618597, 'max_depth': 7, 'subsample': 0.7264841086227345, 'colsample_bytree': 0.936631144923433, 'n_estimators': 353, 'reg_alpha': 6.877098250312662, 'reg_lambda': 0.40966846994355044}. Best is trial 4 with value: 0.9022047369100684.
[I 2026-02-05 06:41:40,458] Trial 5 finished with value: 0.8952569688877706 and parameters: {'learning_rate': 0.1963583227629339, 'max_depth': 3, 'subsample': 0.6370095615982961, 'colsample_bytree': 0.7861224883215847, 'n_estimators': 125, 'reg_alpha': 9.453760304090403, 'reg_lambda': 2.561701376076193}. Best is trial 4 with value: 0.9022047369100684.
[I 2026-02-05 06:41:46,675] Trial 6 finished with value: 0.8801195421054443 and parameters: {'learning_rate': 0.016513881020117367, 'max_depth': 3, 'subsample': 0.9735837607144167, 'colsample_bytree': 0.9447450562715152, 'n_estimators': 327, 'reg_alpha': 0.08610299740456795, 'reg_lambda': 1.878284921348361}. Best is trial 4 with value: 0.9022047369100684.
[I 2026-02-05 06:41:59,315] Trial 7 finished with value: 0.9014326703654358 and parameters: {'learning_rate': 0.09198304894601722, 'max_depth': 10, 'subsample': 0.616996413842143, 'colsample_bytree': 0.9520363773717772, 'n_estimators': 382, 'reg_alpha': 2.3131113425549366, 'reg_lambda': 7.794091432739157}. Best is trial 4 with value: 0.9022047369100684.
[I 2026-02-05 06:42:01,564] Trial 8 finished with value: 0.899244587143302 and parameters: {'learning_rate': 0.18762382510151548, 'max_depth': 6, 'subsample': 0.7733114993947481, 'colsample_bytree': 0.7171955339414986, 'n_estimators': 106, 'reg_alpha': 9.132453751792681, 'reg_lambda': 8.777988764705215}. Best is trial 4 with value: 0.9022047369100684.
[I 2026-02-05 06:42:05,315] Trial 9 finished with value: 0.8712643380109085 and parameters: {'learning_rate': 0.01335026380391316, 'max_depth': 5, 'subsample': 0.6164351695168364, 'colsample_bytree': 0.8987366182774336, 'n_estimators': 150, 'reg_alpha': 9.735487032046175, 'reg_lambda': 2.3981720739152}. Best is trial 4 with value: 0.9022047369100684.
[I 2026-02-05 06:42:10,783] Trial 10 finished with value: 0.9010568070196284 and parameters: {'learning_rate': 0.29669359187782607, 'max_depth': 8, 'subsample': 0.7581524399311117, 'colsample_bytree': 0.6287222493165162, 'n_estimators': 459, 'reg_alpha': 4.846885592254225, 'reg_lambda': 0.14886555290776055}. Best is trial 4 with value: 0.9022047369100684.
[I 2026-02-05 06:42:13,852] Trial 11 finished with value: 0.8988365138020353 and parameters: {'learning_rate': 0.2717055609611948, 'max_depth': 8, 'subsample': 0.7133456239458984, 'colsample_bytree': 0.8124186878766667, 'n_estimators': 243, 'reg_alpha': 7.020835807683231, 'reg_lambda': 4.578884393732265}. Best is trial 4 with value: 0.9022047369100684.
[I 2026-02-05 06:42:18,149] Trial 12 finished with value: 0.9059823400558803 and parameters: {'learning_rate': 0.13308990566750642, 'max_depth': 8, 'subsample': 0.8447174055149851, 'colsample_bytree': 0.9989798394108417, 'n_estimators': 236, 'reg_alpha': 7.630731111751908, 'reg_lambda': 4.886683270280575}. Best is trial 12 with value: 0.9059823400558803.
[I 2026-02-05 06:42:24,367] Trial 13 finished with value: 0.9042649539855403 and parameters: {'learning_rate': 0.13151405794662363, 'max_depth': 9, 'subsample': 0.8631371601665423, 'colsample_bytree': 0.9996391451678145, 'n_estimators': 252, 'reg_alpha': 7.678356498983496, 'reg_lambda': 4.108631575933649}. Best is trial 12 with value: 0.9059823400558803.
[I 2026-02-05 06:42:29,193] Trial 14 finished with value: 0.9050125983574212 and parameters: {'learning_rate': 0.13108368479677437, 'max_depth': 9, 'subsample': 0.8582567411250034, 'colsample_bytree': 0.9948283983266254, 'n_estimators': 251, 'reg_alpha': 8.069079453498656, 'reg_lambda': 6.132422875273612}. Best is trial 12 with value: 0.9059823400558803.
[I 2026-02-05 06:42:35,305] Trial 15 finished with value: 0.9051924930272083 and parameters: {'learning_rate': 0.13274987396906238, 'max_depth': 9, 'subsample': 0.9238708161852767, 'colsample_bytree': 0.9861487675169722, 'n_estimators': 267, 'reg_alpha': 8.113888584483737, 'reg_lambda': 6.310642939702634}. Best is trial 12 with value: 0.9059823400558803.
[I 2026-02-05 06:42:42,255] Trial 16 finished with value: 0.9054968695490926 and parameters: {'learning_rate': 0.0932399777858634, 'max_depth': 9, 'subsample': 0.9696099113873845, 'colsample_bytree': 0.994568626170212, 'n_estimators': 281, 'reg_alpha': 5.130899258241054, 'reg_lambda': 9.608718299115026}. Best is trial 12 with value: 0.9059823400558803.
[I 2026-02-05 06:42:52,747] Trial 17 finished with value: 0.9034837925456389 and parameters: {'learning_rate': 0.08111846608799533, 'max_depth': 6, 'subsample': 0.9861756680502389, 'colsample_bytree': 0.8354073926260795, 'n_estimators': 430, 'reg_alpha': 3.584509061841055, 'reg_lambda': 9.4102971688702}. Best is trial 12 with value: 0.9059823400558803.
[I 2026-02-05 06:43:00,388] Trial 18 finished with value: 0.8965751122812167 and parameters: {'learning_rate': 0.07943842056943727, 'max_depth': 10, 'subsample': 0.9117102223347036, 'colsample_bytree': 0.6023306277800953, 'n_estimators': 211, 'reg_alpha': 5.680058903197798, 'reg_lambda': 3.568080917517337}. Best is trial 12 with value: 0.9059823400558803.
[I 2026-02-05 06:43:06,278] Trial 19 finished with value: 0.9023079564963704 and parameters: {'learning_rate': 0.16354730071193324, 'max_depth': 8, 'subsample': 0.8193218080018289, 'colsample_bytree': 0.7648220600884136, 'n_estimators': 283, 'reg_alpha': 2.255375131156196, 'reg_lambda': 7.773139806067004}. Best is trial 12 with value: 0.9059823400558803.

In [ ]:
X_train_clean, y_train_clean = clean_garbage_labels(X_train_enc, y_train)
X_val_clean, y_val_clean = clean_garbage_labels(X_val_enc, y_val)

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y_train_final = le.fit_transform(y_train_clean)
y_val_final = le.transform(y_val_clean)

print("Kelas final:", le.classes_)

best_params = study_xgb.best_trial.params
print(best_params)

best_params.update({
    'objective': 'multi:softmax',
    'num_class': len(le.classes_),
    'tree_method': 'hist',
    'verbosity': 0,
    'random_state': 42
})

final_xgb_model = xgb.XGBClassifier(**best_params)

final_xgb_model.fit(
    X_train_clean,
    y_train_final
)

Data awal: 7022
Data setelah cleaning: 7022 (Dibuang 0 baris sampah)
Data awal: 1636
Data setelah cleaning: 1636 (Dibuang 0 baris sampah)
Kelas final: ['BAIK' 'SEDANG' 'TIDAK SEHAT']
{'learning_rate': 0.13308990566750642, 'max_depth': 8, 'subsample': 0.8447174055149851, 'colsample_bytree': 0.9989798394108417, 'n_estimators': 236, 'reg_alpha': 7.630731111751908, 'reg_lambda': 4.886683270280575}

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.9989798394108417, device=None,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, feature_types=None, feature_weights=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.13308990566750642,
              max_bin=None, max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=8, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=236, n_jobs=None, num_class=3, ...)

### Forecasting

In [ ]:
!pip install pytorch-lightning pytorch-forecasting

Collecting pytorch-lightning
  Downloading pytorch_lightning-2.6.1-py3-none-any.whl.metadata (21 kB)
Collecting pytorch-forecasting
  Downloading pytorch_forecasting-1.6.1-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: torch>=2.1.0 in /usr/local/lib/python3.12/dist-packages (from pytorch-lightning) (2.9.0+cu126)
Requirement already satisfied: tqdm>=4.57.0 in /usr/local/lib/python3.12/dist-packages (from pytorch-lightning) (4.67.1)
Requirement already satisfied: PyYAML>5.4 in /usr/local/lib/python3.12/dist-packages (from pytorch-lightning) (6.0.3)
Requirement already satisfied: fsspec>=2022.5.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2022.5.0->pytorch-lightning) (2025.3.0)
Collecting torchmetrics>0.7.0 (from pytorch-lightning)
  Downloading torchmetrics-1.8.2-py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: packaging>=23.0 in /usr/local/lib/python3.12/dist-packages (from pytorch-lightning) (25.0)
Requirement already satisfied: typing-extensions>4.5.0 in /usr/local/lib/python3.12/dist-packages (from pytorch-lightning) (4.15.0)
Collecting lightning-utilities>=0.10.0 (from pytorch-lightning)
  Downloading lightning_utilities-0.15.2-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: numpy<=3.0.0 in /usr/local/lib/python3.12/dist-packages (from pytorch-forecasting) (2.0.2)
Collecting lightning<2.7.0,>=2.0.0 (from pytorch-forecasting)
  Downloading lightning-2.6.1-py3-none-any.whl.metadata (44 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.8/44.8 kB 1.4 MB/s eta 0:00:00
Requirement already satisfied: scipy<2.0,>=1.8 in /usr/local/lib/python3.12/dist-packages (from pytorch-forecasting) (1.16.3)
Requirement already satisfied: pandas<3.0.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from pytorch-forecasting) (2.2.2)
Requirement already satisfied: scikit-learn<2.0,>=1.2 in /usr/local/lib/python3.12/dist-packages (from pytorch-forecasting) (1.6.1)
Collecting scikit-base<0.14.0 (from pytorch-forecasting)
  Downloading scikit_base-0.13.1-py3-none-any.whl.metadata (8.8 kB)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2022.5.0->pytorch-lightning) (3.13.3)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from lightning-utilities>=0.10.0->pytorch-lightning) (75.2.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0.0,>=1.3.0->pytorch-forecasting) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0.0,>=1.3.0->pytorch-forecasting) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0.0,>=1.3.0->pytorch-forecasting) (2025.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2.0,>=1.2->pytorch-forecasting) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2.0,>=1.2->pytorch-forecasting) (3.6.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=2.1.0->pytorch-lightning) (3.20.3)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.1.0->pytorch-lightning) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.1.0->pytorch-lightning) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.1.0->pytorch-lightning) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.1.0->pytorch-lightning) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.1.0->pytorch-lightning) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch>=2.1.0->pytorch-lightning) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.1.0->pytorch-lightning) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.1.0->pytorch-lightning) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.1.0->pytorch-lightning) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.1.0->pytorch-lightning) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.1.0->pytorch-lightning) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.1.0->pytorch-lightning) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.1.0->pytorch-lightning) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.1.0->pytorch-lightning) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /usr/local/lib/python3.12/dist-packages (from torch>=2.1.0->pytorch-lightning) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.1.0->pytorch-lightning) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch>=2.1.0->pytorch-lightning) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch>=2.1.0->pytorch-lightning) (1.11.1.6)
Requirement already satisfied: triton==3.5.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.1.0->pytorch-lightning) (3.5.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning) (1.22.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<3.0.0,>=1.3.0->pytorch-forecasting) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.1.0->pytorch-lightning) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.1.0->pytorch-lightning) (3.0.3)
Requirement already satisfied: idna>=2.0 in /usr/local/lib/python3.12/dist-packages (from yarl<2.0,>=1.17.0->aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning) (3.11)
Downloading pytorch_lightning-2.6.1-py3-none-any.whl (857 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 857.3/857.3 kB 35.5 MB/s eta 0:00:00
Downloading pytorch_forecasting-1.6.1-py3-none-any.whl (399 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 399.8/399.8 kB 33.6 MB/s eta 0:00:00
Downloading lightning-2.6.1-py3-none-any.whl (853 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 853.6/853.6 kB 32.0 MB/s eta 0:00:00
Downloading lightning_utilities-0.15.2-py3-none-any.whl (29 kB)
Downloading scikit_base-0.13.1-py3-none-any.whl (159 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 159.8/159.8 kB 11.7 MB/s eta 0:00:00
Downloading torchmetrics-1.8.2-py3-none-any.whl (983 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 983.2/983.2 kB 34.8 MB/s eta 0:00:00
Installing collected packages: scikit-base, lightning-utilities, torchmetrics, pytorch-lightning, lightning, pytorch-forecasting
Successfully installed lightning-2.6.1 lightning-utilities-0.15.2 pytorch-forecasting-1.6.1 pytorch-lightning-2.6.1 scikit-base-0.13.1 torchmetrics-1.8.2

In [ ]:
df_tft = df.copy()
df_tft["tanggal"] = pd.to_datetime(df_tft["tanggal"])
df_tft = df_tft.sort_values(["lokasi_spku","tanggal"]).reset_index(drop=True)

locations = ["DKI1","DKI2","DKI3","DKI4","DKI5"]
targets   = ["pm10","so2","co","o3","no2"]

max_encoder_length = 60
max_prediction_length = 91

import lightning.pytorch as pl
from lightning.pytorch import Trainer

from pytorch_forecasting import TimeSeriesDataSet
from pytorch_forecasting import TemporalFusionTransformer
from pytorch_forecasting.metrics import QuantileLoss
from pytorch_forecasting.data import GroupNormalizer

tft_models = {}
tft_datasets = {}

for loc in locations:

    df_loc = df_tft[df_tft["lokasi_spku"] == loc].copy()
    df_loc = df_loc.sort_values("tanggal")

    # time index khusus lokasi ini
    df_loc["time_idx"] = np.arange(len(df_loc))

    for target in targets:

        print(f"Training TFT -> {loc} | {target}")

        dataset = TimeSeriesDataSet(
            df_loc,
            time_idx="time_idx",
            target=target,

            group_ids=["lokasi_spku"],

            min_encoder_length=max_encoder_length,
            max_encoder_length=max_encoder_length,

            min_prediction_length=max_prediction_length,
            max_prediction_length=max_prediction_length,

            static_categoricals=["lokasi_spku"],

            time_varying_known_reals=[
                "time_idx"
            ],

            time_varying_unknown_reals=[
                target
            ],

            target_normalizer=GroupNormalizer(
                groups=["lokasi_spku"]
            )
        )

        train_loader = dataset.to_dataloader(
            train=True,
            batch_size=32,
            num_workers=0
        )

        tft = TemporalFusionTransformer.from_dataset(
            dataset,
            learning_rate=0.03,
            hidden_size=16,
            attention_head_size=2,
            dropout=0.1,
            hidden_continuous_size=8,
            loss=QuantileLoss(),
            reduce_on_plateau_patience=3
        )

        trainer = Trainer(
            max_epochs=20,
            accelerator="auto",
            enable_checkpointing=False,
            logger=False,
            gradient_clip_val=0.1
        )

        trainer.fit(tft, train_loader)

        tft_models[(loc, target)] = tft
        tft_datasets[(loc, target)] = dataset

Training TFT -> DKI1 | pm10

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

┏━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃    ┃ Name                               ┃ Type                            ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0  │ loss                               │ QuantileLoss                    │      0 │ train │     0 │
│ 1  │ logging_metrics                    │ ModuleList                      │      0 │ train │     0 │
│ 2  │ input_embeddings                   │ MultiEmbedding                  │      1 │ train │     0 │
│ 3  │ prescalers                         │ ModuleDict                      │     32 │ train │     0 │
│ 4  │ static_variable_selection          │ VariableSelectionNetwork        │     48 │ train │     0 │
│ 5  │ encoder_variable_selection         │ VariableSelectionNetwork        │  1.2 K │ train │     0 │
│ 6  │ decoder_variable_selection         │ VariableSelectionNetwork        │    528 │ train │     0 │
│ 7  │ static_context_variable_selection  │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 8  │ static_context_initial_hidden_lstm │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 9  │ static_context_initial_cell_lstm   │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 10 │ static_context_enrichment          │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 11 │ lstm_encoder                       │ LSTM                            │  2.2 K │ train │     0 │
│ 12 │ lstm_decoder                       │ LSTM                            │  2.2 K │ train │     0 │
│ 13 │ post_lstm_gate_encoder             │ GatedLinearUnit                 │    544 │ train │     0 │
│ 14 │ post_lstm_add_norm_encoder         │ AddNorm                         │     32 │ train │     0 │
│ 15 │ static_enrichment                  │ GatedResidualNetwork            │  1.4 K │ train │     0 │
│ 16 │ multihead_attn                     │ InterpretableMultiHeadAttention │    808 │ train │     0 │
│ 17 │ post_attn_gate_norm                │ GateAddNorm                     │    576 │ train │     0 │
│ 18 │ pos_wise_ff                        │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 19 │ pre_output_gate_norm               │ GateAddNorm                     │    576 │ train │     0 │
│ 20 │ output_layer                       │ Linear                          │    119 │ train │     0 │
└────┴────────────────────────────────────┴─────────────────────────────────┴────────┴───────┴───────┘

Trainable params: 15.7 K
Non-trainable params: 0
Total params: 15.7 K
Total estimated model params size (MB): 0
Modules in train mode: 177
Modules in eval mode: 0
Total FLOPs: 0

Output()

INFO: `Trainer.fit` stopped: `max_epochs=20` reached.
INFO:lightning.pytorch.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=20` reached.

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Training TFT -> DKI1 | so2

┏━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃    ┃ Name                               ┃ Type                            ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0  │ loss                               │ QuantileLoss                    │      0 │ train │     0 │
│ 1  │ logging_metrics                    │ ModuleList                      │      0 │ train │     0 │
│ 2  │ input_embeddings                   │ MultiEmbedding                  │      1 │ train │     0 │
│ 3  │ prescalers                         │ ModuleDict                      │     32 │ train │     0 │
│ 4  │ static_variable_selection          │ VariableSelectionNetwork        │     48 │ train │     0 │
│ 5  │ encoder_variable_selection         │ VariableSelectionNetwork        │  1.2 K │ train │     0 │
│ 6  │ decoder_variable_selection         │ VariableSelectionNetwork        │    528 │ train │     0 │
│ 7  │ static_context_variable_selection  │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 8  │ static_context_initial_hidden_lstm │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 9  │ static_context_initial_cell_lstm   │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 10 │ static_context_enrichment          │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 11 │ lstm_encoder                       │ LSTM                            │  2.2 K │ train │     0 │
│ 12 │ lstm_decoder                       │ LSTM                            │  2.2 K │ train │     0 │
│ 13 │ post_lstm_gate_encoder             │ GatedLinearUnit                 │    544 │ train │     0 │
│ 14 │ post_lstm_add_norm_encoder         │ AddNorm                         │     32 │ train │     0 │
│ 15 │ static_enrichment                  │ GatedResidualNetwork            │  1.4 K │ train │     0 │
│ 16 │ multihead_attn                     │ InterpretableMultiHeadAttention │    808 │ train │     0 │
│ 17 │ post_attn_gate_norm                │ GateAddNorm                     │    576 │ train │     0 │
│ 18 │ pos_wise_ff                        │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 19 │ pre_output_gate_norm               │ GateAddNorm                     │    576 │ train │     0 │
│ 20 │ output_layer                       │ Linear                          │    119 │ train │     0 │
└────┴────────────────────────────────────┴─────────────────────────────────┴────────┴───────┴───────┘

Trainable params: 15.7 K
Non-trainable params: 0
Total params: 15.7 K
Total estimated model params size (MB): 0
Modules in train mode: 177
Modules in eval mode: 0
Total FLOPs: 0

Output()

INFO: `Trainer.fit` stopped: `max_epochs=20` reached.
INFO:lightning.pytorch.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=20` reached.

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Training TFT -> DKI1 | co

┏━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃    ┃ Name                               ┃ Type                            ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0  │ loss                               │ QuantileLoss                    │      0 │ train │     0 │
│ 1  │ logging_metrics                    │ ModuleList                      │      0 │ train │     0 │
│ 2  │ input_embeddings                   │ MultiEmbedding                  │      1 │ train │     0 │
│ 3  │ prescalers                         │ ModuleDict                      │     32 │ train │     0 │
│ 4  │ static_variable_selection          │ VariableSelectionNetwork        │     48 │ train │     0 │
│ 5  │ encoder_variable_selection         │ VariableSelectionNetwork        │  1.2 K │ train │     0 │
│ 6  │ decoder_variable_selection         │ VariableSelectionNetwork        │    528 │ train │     0 │
│ 7  │ static_context_variable_selection  │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 8  │ static_context_initial_hidden_lstm │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 9  │ static_context_initial_cell_lstm   │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 10 │ static_context_enrichment          │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 11 │ lstm_encoder                       │ LSTM                            │  2.2 K │ train │     0 │
│ 12 │ lstm_decoder                       │ LSTM                            │  2.2 K │ train │     0 │
│ 13 │ post_lstm_gate_encoder             │ GatedLinearUnit                 │    544 │ train │     0 │
│ 14 │ post_lstm_add_norm_encoder         │ AddNorm                         │     32 │ train │     0 │
│ 15 │ static_enrichment                  │ GatedResidualNetwork            │  1.4 K │ train │     0 │
│ 16 │ multihead_attn                     │ InterpretableMultiHeadAttention │    808 │ train │     0 │
│ 17 │ post_attn_gate_norm                │ GateAddNorm                     │    576 │ train │     0 │
│ 18 │ pos_wise_ff                        │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 19 │ pre_output_gate_norm               │ GateAddNorm                     │    576 │ train │     0 │
│ 20 │ output_layer                       │ Linear                          │    119 │ train │     0 │
└────┴────────────────────────────────────┴─────────────────────────────────┴────────┴───────┴───────┘

Trainable params: 15.7 K
Non-trainable params: 0
Total params: 15.7 K
Total estimated model params size (MB): 0
Modules in train mode: 177
Modules in eval mode: 0
Total FLOPs: 0

Output()

INFO: `Trainer.fit` stopped: `max_epochs=20` reached.
INFO:lightning.pytorch.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=20` reached.

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Training TFT -> DKI1 | o3

┏━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃    ┃ Name                               ┃ Type                            ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0  │ loss                               │ QuantileLoss                    │      0 │ train │     0 │
│ 1  │ logging_metrics                    │ ModuleList                      │      0 │ train │     0 │
│ 2  │ input_embeddings                   │ MultiEmbedding                  │      1 │ train │     0 │
│ 3  │ prescalers                         │ ModuleDict                      │     32 │ train │     0 │
│ 4  │ static_variable_selection          │ VariableSelectionNetwork        │     48 │ train │     0 │
│ 5  │ encoder_variable_selection         │ VariableSelectionNetwork        │  1.2 K │ train │     0 │
│ 6  │ decoder_variable_selection         │ VariableSelectionNetwork        │    528 │ train │     0 │
│ 7  │ static_context_variable_selection  │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 8  │ static_context_initial_hidden_lstm │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 9  │ static_context_initial_cell_lstm   │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 10 │ static_context_enrichment          │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 11 │ lstm_encoder                       │ LSTM                            │  2.2 K │ train │     0 │
│ 12 │ lstm_decoder                       │ LSTM                            │  2.2 K │ train │     0 │
│ 13 │ post_lstm_gate_encoder             │ GatedLinearUnit                 │    544 │ train │     0 │
│ 14 │ post_lstm_add_norm_encoder         │ AddNorm                         │     32 │ train │     0 │
│ 15 │ static_enrichment                  │ GatedResidualNetwork            │  1.4 K │ train │     0 │
│ 16 │ multihead_attn                     │ InterpretableMultiHeadAttention │    808 │ train │     0 │
│ 17 │ post_attn_gate_norm                │ GateAddNorm                     │    576 │ train │     0 │
│ 18 │ pos_wise_ff                        │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 19 │ pre_output_gate_norm               │ GateAddNorm                     │    576 │ train │     0 │
│ 20 │ output_layer                       │ Linear                          │    119 │ train │     0 │
└────┴────────────────────────────────────┴─────────────────────────────────┴────────┴───────┴───────┘

Trainable params: 15.7 K
Non-trainable params: 0
Total params: 15.7 K
Total estimated model params size (MB): 0
Modules in train mode: 177
Modules in eval mode: 0
Total FLOPs: 0

Output()

INFO: `Trainer.fit` stopped: `max_epochs=20` reached.
INFO:lightning.pytorch.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=20` reached.

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Training TFT -> DKI1 | no2

┏━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃    ┃ Name                               ┃ Type                            ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0  │ loss                               │ QuantileLoss                    │      0 │ train │     0 │
│ 1  │ logging_metrics                    │ ModuleList                      │      0 │ train │     0 │
│ 2  │ input_embeddings                   │ MultiEmbedding                  │      1 │ train │     0 │
│ 3  │ prescalers                         │ ModuleDict                      │     32 │ train │     0 │
│ 4  │ static_variable_selection          │ VariableSelectionNetwork        │     48 │ train │     0 │
│ 5  │ encoder_variable_selection         │ VariableSelectionNetwork        │  1.2 K │ train │     0 │
│ 6  │ decoder_variable_selection         │ VariableSelectionNetwork        │    528 │ train │     0 │
│ 7  │ static_context_variable_selection  │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 8  │ static_context_initial_hidden_lstm │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 9  │ static_context_initial_cell_lstm   │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 10 │ static_context_enrichment          │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 11 │ lstm_encoder                       │ LSTM                            │  2.2 K │ train │     0 │
│ 12 │ lstm_decoder                       │ LSTM                            │  2.2 K │ train │     0 │
│ 13 │ post_lstm_gate_encoder             │ GatedLinearUnit                 │    544 │ train │     0 │
│ 14 │ post_lstm_add_norm_encoder         │ AddNorm                         │     32 │ train │     0 │
│ 15 │ static_enrichment                  │ GatedResidualNetwork            │  1.4 K │ train │     0 │
│ 16 │ multihead_attn                     │ InterpretableMultiHeadAttention │    808 │ train │     0 │
│ 17 │ post_attn_gate_norm                │ GateAddNorm                     │    576 │ train │     0 │
│ 18 │ pos_wise_ff                        │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 19 │ pre_output_gate_norm               │ GateAddNorm                     │    576 │ train │     0 │
│ 20 │ output_layer                       │ Linear                          │    119 │ train │     0 │
└────┴────────────────────────────────────┴─────────────────────────────────┴────────┴───────┴───────┘

Trainable params: 15.7 K
Non-trainable params: 0
Total params: 15.7 K
Total estimated model params size (MB): 0
Modules in train mode: 177
Modules in eval mode: 0
Total FLOPs: 0

Output()

INFO: `Trainer.fit` stopped: `max_epochs=20` reached.
INFO:lightning.pytorch.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=20` reached.

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Training TFT -> DKI2 | pm10

┏━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃    ┃ Name                               ┃ Type                            ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0  │ loss                               │ QuantileLoss                    │      0 │ train │     0 │
│ 1  │ logging_metrics                    │ ModuleList                      │      0 │ train │     0 │
│ 2  │ input_embeddings                   │ MultiEmbedding                  │      1 │ train │     0 │
│ 3  │ prescalers                         │ ModuleDict                      │     32 │ train │     0 │
│ 4  │ static_variable_selection          │ VariableSelectionNetwork        │     48 │ train │     0 │
│ 5  │ encoder_variable_selection         │ VariableSelectionNetwork        │  1.2 K │ train │     0 │
│ 6  │ decoder_variable_selection         │ VariableSelectionNetwork        │    528 │ train │     0 │
│ 7  │ static_context_variable_selection  │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 8  │ static_context_initial_hidden_lstm │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 9  │ static_context_initial_cell_lstm   │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 10 │ static_context_enrichment          │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 11 │ lstm_encoder                       │ LSTM                            │  2.2 K │ train │     0 │
│ 12 │ lstm_decoder                       │ LSTM                            │  2.2 K │ train │     0 │
│ 13 │ post_lstm_gate_encoder             │ GatedLinearUnit                 │    544 │ train │     0 │
│ 14 │ post_lstm_add_norm_encoder         │ AddNorm                         │     32 │ train │     0 │
│ 15 │ static_enrichment                  │ GatedResidualNetwork            │  1.4 K │ train │     0 │
│ 16 │ multihead_attn                     │ InterpretableMultiHeadAttention │    808 │ train │     0 │
│ 17 │ post_attn_gate_norm                │ GateAddNorm                     │    576 │ train │     0 │
│ 18 │ pos_wise_ff                        │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 19 │ pre_output_gate_norm               │ GateAddNorm                     │    576 │ train │     0 │
│ 20 │ output_layer                       │ Linear                          │    119 │ train │     0 │
└────┴────────────────────────────────────┴─────────────────────────────────┴────────┴───────┴───────┘

Trainable params: 15.7 K
Non-trainable params: 0
Total params: 15.7 K
Total estimated model params size (MB): 0
Modules in train mode: 177
Modules in eval mode: 0
Total FLOPs: 0

Output()

INFO: `Trainer.fit` stopped: `max_epochs=20` reached.
INFO:lightning.pytorch.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=20` reached.

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Training TFT -> DKI2 | so2

┏━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃    ┃ Name                               ┃ Type                            ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0  │ loss                               │ QuantileLoss                    │      0 │ train │     0 │
│ 1  │ logging_metrics                    │ ModuleList                      │      0 │ train │     0 │
│ 2  │ input_embeddings                   │ MultiEmbedding                  │      1 │ train │     0 │
│ 3  │ prescalers                         │ ModuleDict                      │     32 │ train │     0 │
│ 4  │ static_variable_selection          │ VariableSelectionNetwork        │     48 │ train │     0 │
│ 5  │ encoder_variable_selection         │ VariableSelectionNetwork        │  1.2 K │ train │     0 │
│ 6  │ decoder_variable_selection         │ VariableSelectionNetwork        │    528 │ train │     0 │
│ 7  │ static_context_variable_selection  │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 8  │ static_context_initial_hidden_lstm │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 9  │ static_context_initial_cell_lstm   │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 10 │ static_context_enrichment          │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 11 │ lstm_encoder                       │ LSTM                            │  2.2 K │ train │     0 │
│ 12 │ lstm_decoder                       │ LSTM                            │  2.2 K │ train │     0 │
│ 13 │ post_lstm_gate_encoder             │ GatedLinearUnit                 │    544 │ train │     0 │
│ 14 │ post_lstm_add_norm_encoder         │ AddNorm                         │     32 │ train │     0 │
│ 15 │ static_enrichment                  │ GatedResidualNetwork            │  1.4 K │ train │     0 │
│ 16 │ multihead_attn                     │ InterpretableMultiHeadAttention │    808 │ train │     0 │
│ 17 │ post_attn_gate_norm                │ GateAddNorm                     │    576 │ train │     0 │
│ 18 │ pos_wise_ff                        │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 19 │ pre_output_gate_norm               │ GateAddNorm                     │    576 │ train │     0 │
│ 20 │ output_layer                       │ Linear                          │    119 │ train │     0 │
└────┴────────────────────────────────────┴─────────────────────────────────┴────────┴───────┴───────┘

Trainable params: 15.7 K
Non-trainable params: 0
Total params: 15.7 K
Total estimated model params size (MB): 0
Modules in train mode: 177
Modules in eval mode: 0
Total FLOPs: 0

Output()

INFO: `Trainer.fit` stopped: `max_epochs=20` reached.
INFO:lightning.pytorch.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=20` reached.

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Training TFT -> DKI2 | co

┏━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃    ┃ Name                               ┃ Type                            ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0  │ loss                               │ QuantileLoss                    │      0 │ train │     0 │
│ 1  │ logging_metrics                    │ ModuleList                      │      0 │ train │     0 │
│ 2  │ input_embeddings                   │ MultiEmbedding                  │      1 │ train │     0 │
│ 3  │ prescalers                         │ ModuleDict                      │     32 │ train │     0 │
│ 4  │ static_variable_selection          │ VariableSelectionNetwork        │     48 │ train │     0 │
│ 5  │ encoder_variable_selection         │ VariableSelectionNetwork        │  1.2 K │ train │     0 │
│ 6  │ decoder_variable_selection         │ VariableSelectionNetwork        │    528 │ train │     0 │
│ 7  │ static_context_variable_selection  │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 8  │ static_context_initial_hidden_lstm │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 9  │ static_context_initial_cell_lstm   │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 10 │ static_context_enrichment          │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 11 │ lstm_encoder                       │ LSTM                            │  2.2 K │ train │     0 │
│ 12 │ lstm_decoder                       │ LSTM                            │  2.2 K │ train │     0 │
│ 13 │ post_lstm_gate_encoder             │ GatedLinearUnit                 │    544 │ train │     0 │
│ 14 │ post_lstm_add_norm_encoder         │ AddNorm                         │     32 │ train │     0 │
│ 15 │ static_enrichment                  │ GatedResidualNetwork            │  1.4 K │ train │     0 │
│ 16 │ multihead_attn                     │ InterpretableMultiHeadAttention │    808 │ train │     0 │
│ 17 │ post_attn_gate_norm                │ GateAddNorm                     │    576 │ train │     0 │
│ 18 │ pos_wise_ff                        │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 19 │ pre_output_gate_norm               │ GateAddNorm                     │    576 │ train │     0 │
│ 20 │ output_layer                       │ Linear                          │    119 │ train │     0 │
└────┴────────────────────────────────────┴─────────────────────────────────┴────────┴───────┴───────┘

Trainable params: 15.7 K
Non-trainable params: 0
Total params: 15.7 K
Total estimated model params size (MB): 0
Modules in train mode: 177
Modules in eval mode: 0
Total FLOPs: 0

Output()

INFO: `Trainer.fit` stopped: `max_epochs=20` reached.
INFO:lightning.pytorch.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=20` reached.

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Training TFT -> DKI2 | o3

┏━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃    ┃ Name                               ┃ Type                            ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0  │ loss                               │ QuantileLoss                    │      0 │ train │     0 │
│ 1  │ logging_metrics                    │ ModuleList                      │      0 │ train │     0 │
│ 2  │ input_embeddings                   │ MultiEmbedding                  │      1 │ train │     0 │
│ 3  │ prescalers                         │ ModuleDict                      │     32 │ train │     0 │
│ 4  │ static_variable_selection          │ VariableSelectionNetwork        │     48 │ train │     0 │
│ 5  │ encoder_variable_selection         │ VariableSelectionNetwork        │  1.2 K │ train │     0 │
│ 6  │ decoder_variable_selection         │ VariableSelectionNetwork        │    528 │ train │     0 │
│ 7  │ static_context_variable_selection  │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 8  │ static_context_initial_hidden_lstm │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 9  │ static_context_initial_cell_lstm   │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 10 │ static_context_enrichment          │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 11 │ lstm_encoder                       │ LSTM                            │  2.2 K │ train │     0 │
│ 12 │ lstm_decoder                       │ LSTM                            │  2.2 K │ train │     0 │
│ 13 │ post_lstm_gate_encoder             │ GatedLinearUnit                 │    544 │ train │     0 │
│ 14 │ post_lstm_add_norm_encoder         │ AddNorm                         │     32 │ train │     0 │
│ 15 │ static_enrichment                  │ GatedResidualNetwork            │  1.4 K │ train │     0 │
│ 16 │ multihead_attn                     │ InterpretableMultiHeadAttention │    808 │ train │     0 │
│ 17 │ post_attn_gate_norm                │ GateAddNorm                     │    576 │ train │     0 │
│ 18 │ pos_wise_ff                        │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 19 │ pre_output_gate_norm               │ GateAddNorm                     │    576 │ train │     0 │
│ 20 │ output_layer                       │ Linear                          │    119 │ train │     0 │
└────┴────────────────────────────────────┴─────────────────────────────────┴────────┴───────┴───────┘

Trainable params: 15.7 K
Non-trainable params: 0
Total params: 15.7 K
Total estimated model params size (MB): 0
Modules in train mode: 177
Modules in eval mode: 0
Total FLOPs: 0

Output()

INFO: `Trainer.fit` stopped: `max_epochs=20` reached.
INFO:lightning.pytorch.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=20` reached.

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Training TFT -> DKI2 | no2

┏━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃    ┃ Name                               ┃ Type                            ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0  │ loss                               │ QuantileLoss                    │      0 │ train │     0 │
│ 1  │ logging_metrics                    │ ModuleList                      │      0 │ train │     0 │
│ 2  │ input_embeddings                   │ MultiEmbedding                  │      1 │ train │     0 │
│ 3  │ prescalers                         │ ModuleDict                      │     32 │ train │     0 │
│ 4  │ static_variable_selection          │ VariableSelectionNetwork        │     48 │ train │     0 │
│ 5  │ encoder_variable_selection         │ VariableSelectionNetwork        │  1.2 K │ train │     0 │
│ 6  │ decoder_variable_selection         │ VariableSelectionNetwork        │    528 │ train │     0 │
│ 7  │ static_context_variable_selection  │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 8  │ static_context_initial_hidden_lstm │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 9  │ static_context_initial_cell_lstm   │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 10 │ static_context_enrichment          │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 11 │ lstm_encoder                       │ LSTM                            │  2.2 K │ train │     0 │
│ 12 │ lstm_decoder                       │ LSTM                            │  2.2 K │ train │     0 │
│ 13 │ post_lstm_gate_encoder             │ GatedLinearUnit                 │    544 │ train │     0 │
│ 14 │ post_lstm_add_norm_encoder         │ AddNorm                         │     32 │ train │     0 │
│ 15 │ static_enrichment                  │ GatedResidualNetwork            │  1.4 K │ train │     0 │
│ 16 │ multihead_attn                     │ InterpretableMultiHeadAttention │    808 │ train │     0 │
│ 17 │ post_attn_gate_norm                │ GateAddNorm                     │    576 │ train │     0 │
│ 18 │ pos_wise_ff                        │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 19 │ pre_output_gate_norm               │ GateAddNorm                     │    576 │ train │     0 │
│ 20 │ output_layer                       │ Linear                          │    119 │ train │     0 │
└────┴────────────────────────────────────┴─────────────────────────────────┴────────┴───────┴───────┘

Trainable params: 15.7 K
Non-trainable params: 0
Total params: 15.7 K
Total estimated model params size (MB): 0
Modules in train mode: 177
Modules in eval mode: 0
Total FLOPs: 0

Output()

INFO: `Trainer.fit` stopped: `max_epochs=20` reached.
INFO:lightning.pytorch.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=20` reached.

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Training TFT -> DKI3 | pm10

┏━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃    ┃ Name                               ┃ Type                            ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0  │ loss                               │ QuantileLoss                    │      0 │ train │     0 │
│ 1  │ logging_metrics                    │ ModuleList                      │      0 │ train │     0 │
│ 2  │ input_embeddings                   │ MultiEmbedding                  │      1 │ train │     0 │
│ 3  │ prescalers                         │ ModuleDict                      │     32 │ train │     0 │
│ 4  │ static_variable_selection          │ VariableSelectionNetwork        │     48 │ train │     0 │
│ 5  │ encoder_variable_selection         │ VariableSelectionNetwork        │  1.2 K │ train │     0 │
│ 6  │ decoder_variable_selection         │ VariableSelectionNetwork        │    528 │ train │     0 │
│ 7  │ static_context_variable_selection  │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 8  │ static_context_initial_hidden_lstm │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 9  │ static_context_initial_cell_lstm   │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 10 │ static_context_enrichment          │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 11 │ lstm_encoder                       │ LSTM                            │  2.2 K │ train │     0 │
│ 12 │ lstm_decoder                       │ LSTM                            │  2.2 K │ train │     0 │
│ 13 │ post_lstm_gate_encoder             │ GatedLinearUnit                 │    544 │ train │     0 │
│ 14 │ post_lstm_add_norm_encoder         │ AddNorm                         │     32 │ train │     0 │
│ 15 │ static_enrichment                  │ GatedResidualNetwork            │  1.4 K │ train │     0 │
│ 16 │ multihead_attn                     │ InterpretableMultiHeadAttention │    808 │ train │     0 │
│ 17 │ post_attn_gate_norm                │ GateAddNorm                     │    576 │ train │     0 │
│ 18 │ pos_wise_ff                        │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 19 │ pre_output_gate_norm               │ GateAddNorm                     │    576 │ train │     0 │
│ 20 │ output_layer                       │ Linear                          │    119 │ train │     0 │
└────┴────────────────────────────────────┴─────────────────────────────────┴────────┴───────┴───────┘

Trainable params: 15.7 K
Non-trainable params: 0
Total params: 15.7 K
Total estimated model params size (MB): 0
Modules in train mode: 177
Modules in eval mode: 0
Total FLOPs: 0

Output()

INFO: `Trainer.fit` stopped: `max_epochs=20` reached.
INFO:lightning.pytorch.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=20` reached.

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Training TFT -> DKI3 | so2

┏━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃    ┃ Name                               ┃ Type                            ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0  │ loss                               │ QuantileLoss                    │      0 │ train │     0 │
│ 1  │ logging_metrics                    │ ModuleList                      │      0 │ train │     0 │
│ 2  │ input_embeddings                   │ MultiEmbedding                  │      1 │ train │     0 │
│ 3  │ prescalers                         │ ModuleDict                      │     32 │ train │     0 │
│ 4  │ static_variable_selection          │ VariableSelectionNetwork        │     48 │ train │     0 │
│ 5  │ encoder_variable_selection         │ VariableSelectionNetwork        │  1.2 K │ train │     0 │
│ 6  │ decoder_variable_selection         │ VariableSelectionNetwork        │    528 │ train │     0 │
│ 7  │ static_context_variable_selection  │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 8  │ static_context_initial_hidden_lstm │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 9  │ static_context_initial_cell_lstm   │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 10 │ static_context_enrichment          │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 11 │ lstm_encoder                       │ LSTM                            │  2.2 K │ train │     0 │
│ 12 │ lstm_decoder                       │ LSTM                            │  2.2 K │ train │     0 │
│ 13 │ post_lstm_gate_encoder             │ GatedLinearUnit                 │    544 │ train │     0 │
│ 14 │ post_lstm_add_norm_encoder         │ AddNorm                         │     32 │ train │     0 │
│ 15 │ static_enrichment                  │ GatedResidualNetwork            │  1.4 K │ train │     0 │
│ 16 │ multihead_attn                     │ InterpretableMultiHeadAttention │    808 │ train │     0 │
│ 17 │ post_attn_gate_norm                │ GateAddNorm                     │    576 │ train │     0 │
│ 18 │ pos_wise_ff                        │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 19 │ pre_output_gate_norm               │ GateAddNorm                     │    576 │ train │     0 │
│ 20 │ output_layer                       │ Linear                          │    119 │ train │     0 │
└────┴────────────────────────────────────┴─────────────────────────────────┴────────┴───────┴───────┘

Trainable params: 15.7 K
Non-trainable params: 0
Total params: 15.7 K
Total estimated model params size (MB): 0
Modules in train mode: 177
Modules in eval mode: 0
Total FLOPs: 0

Output()

INFO: `Trainer.fit` stopped: `max_epochs=20` reached.
INFO:lightning.pytorch.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=20` reached.

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Training TFT -> DKI3 | co

┏━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃    ┃ Name                               ┃ Type                            ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0  │ loss                               │ QuantileLoss                    │      0 │ train │     0 │
│ 1  │ logging_metrics                    │ ModuleList                      │      0 │ train │     0 │
│ 2  │ input_embeddings                   │ MultiEmbedding                  │      1 │ train │     0 │
│ 3  │ prescalers                         │ ModuleDict                      │     32 │ train │     0 │
│ 4  │ static_variable_selection          │ VariableSelectionNetwork        │     48 │ train │     0 │
│ 5  │ encoder_variable_selection         │ VariableSelectionNetwork        │  1.2 K │ train │     0 │
│ 6  │ decoder_variable_selection         │ VariableSelectionNetwork        │    528 │ train │     0 │
│ 7  │ static_context_variable_selection  │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 8  │ static_context_initial_hidden_lstm │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 9  │ static_context_initial_cell_lstm   │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 10 │ static_context_enrichment          │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 11 │ lstm_encoder                       │ LSTM                            │  2.2 K │ train │     0 │
│ 12 │ lstm_decoder                       │ LSTM                            │  2.2 K │ train │     0 │
│ 13 │ post_lstm_gate_encoder             │ GatedLinearUnit                 │    544 │ train │     0 │
│ 14 │ post_lstm_add_norm_encoder         │ AddNorm                         │     32 │ train │     0 │
│ 15 │ static_enrichment                  │ GatedResidualNetwork            │  1.4 K │ train │     0 │
│ 16 │ multihead_attn                     │ InterpretableMultiHeadAttention │    808 │ train │     0 │
│ 17 │ post_attn_gate_norm                │ GateAddNorm                     │    576 │ train │     0 │
│ 18 │ pos_wise_ff                        │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 19 │ pre_output_gate_norm               │ GateAddNorm                     │    576 │ train │     0 │
│ 20 │ output_layer                       │ Linear                          │    119 │ train │     0 │
└────┴────────────────────────────────────┴─────────────────────────────────┴────────┴───────┴───────┘

Trainable params: 15.7 K
Non-trainable params: 0
Total params: 15.7 K
Total estimated model params size (MB): 0
Modules in train mode: 177
Modules in eval mode: 0
Total FLOPs: 0

Output()

INFO: `Trainer.fit` stopped: `max_epochs=20` reached.
INFO:lightning.pytorch.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=20` reached.

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Training TFT -> DKI3 | o3

┏━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃    ┃ Name                               ┃ Type                            ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0  │ loss                               │ QuantileLoss                    │      0 │ train │     0 │
│ 1  │ logging_metrics                    │ ModuleList                      │      0 │ train │     0 │
│ 2  │ input_embeddings                   │ MultiEmbedding                  │      1 │ train │     0 │
│ 3  │ prescalers                         │ ModuleDict                      │     32 │ train │     0 │
│ 4  │ static_variable_selection          │ VariableSelectionNetwork        │     48 │ train │     0 │
│ 5  │ encoder_variable_selection         │ VariableSelectionNetwork        │  1.2 K │ train │     0 │
│ 6  │ decoder_variable_selection         │ VariableSelectionNetwork        │    528 │ train │     0 │
│ 7  │ static_context_variable_selection  │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 8  │ static_context_initial_hidden_lstm │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 9  │ static_context_initial_cell_lstm   │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 10 │ static_context_enrichment          │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 11 │ lstm_encoder                       │ LSTM                            │  2.2 K │ train │     0 │
│ 12 │ lstm_decoder                       │ LSTM                            │  2.2 K │ train │     0 │
│ 13 │ post_lstm_gate_encoder             │ GatedLinearUnit                 │    544 │ train │     0 │
│ 14 │ post_lstm_add_norm_encoder         │ AddNorm                         │     32 │ train │     0 │
│ 15 │ static_enrichment                  │ GatedResidualNetwork            │  1.4 K │ train │     0 │
│ 16 │ multihead_attn                     │ InterpretableMultiHeadAttention │    808 │ train │     0 │
│ 17 │ post_attn_gate_norm                │ GateAddNorm                     │    576 │ train │     0 │
│ 18 │ pos_wise_ff                        │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 19 │ pre_output_gate_norm               │ GateAddNorm                     │    576 │ train │     0 │
│ 20 │ output_layer                       │ Linear                          │    119 │ train │     0 │
└────┴────────────────────────────────────┴─────────────────────────────────┴────────┴───────┴───────┘

Trainable params: 15.7 K
Non-trainable params: 0
Total params: 15.7 K
Total estimated model params size (MB): 0
Modules in train mode: 177
Modules in eval mode: 0
Total FLOPs: 0

Output()

INFO: `Trainer.fit` stopped: `max_epochs=20` reached.
INFO:lightning.pytorch.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=20` reached.

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Training TFT -> DKI3 | no2

┏━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃    ┃ Name                               ┃ Type                            ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0  │ loss                               │ QuantileLoss                    │      0 │ train │     0 │
│ 1  │ logging_metrics                    │ ModuleList                      │      0 │ train │     0 │
│ 2  │ input_embeddings                   │ MultiEmbedding                  │      1 │ train │     0 │
│ 3  │ prescalers                         │ ModuleDict                      │     32 │ train │     0 │
│ 4  │ static_variable_selection          │ VariableSelectionNetwork        │     48 │ train │     0 │
│ 5  │ encoder_variable_selection         │ VariableSelectionNetwork        │  1.2 K │ train │     0 │
│ 6  │ decoder_variable_selection         │ VariableSelectionNetwork        │    528 │ train │     0 │
│ 7  │ static_context_variable_selection  │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 8  │ static_context_initial_hidden_lstm │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 9  │ static_context_initial_cell_lstm   │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 10 │ static_context_enrichment          │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 11 │ lstm_encoder                       │ LSTM                            │  2.2 K │ train │     0 │
│ 12 │ lstm_decoder                       │ LSTM                            │  2.2 K │ train │     0 │
│ 13 │ post_lstm_gate_encoder             │ GatedLinearUnit                 │    544 │ train │     0 │
│ 14 │ post_lstm_add_norm_encoder         │ AddNorm                         │     32 │ train │     0 │
│ 15 │ static_enrichment                  │ GatedResidualNetwork            │  1.4 K │ train │     0 │
│ 16 │ multihead_attn                     │ InterpretableMultiHeadAttention │    808 │ train │     0 │
│ 17 │ post_attn_gate_norm                │ GateAddNorm                     │    576 │ train │     0 │
│ 18 │ pos_wise_ff                        │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 19 │ pre_output_gate_norm               │ GateAddNorm                     │    576 │ train │     0 │
│ 20 │ output_layer                       │ Linear                          │    119 │ train │     0 │
└────┴────────────────────────────────────┴─────────────────────────────────┴────────┴───────┴───────┘

Trainable params: 15.7 K
Non-trainable params: 0
Total params: 15.7 K
Total estimated model params size (MB): 0
Modules in train mode: 177
Modules in eval mode: 0
Total FLOPs: 0

Output()

INFO: `Trainer.fit` stopped: `max_epochs=20` reached.
INFO:lightning.pytorch.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=20` reached.

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Training TFT -> DKI4 | pm10

┏━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃    ┃ Name                               ┃ Type                            ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0  │ loss                               │ QuantileLoss                    │      0 │ train │     0 │
│ 1  │ logging_metrics                    │ ModuleList                      │      0 │ train │     0 │
│ 2  │ input_embeddings                   │ MultiEmbedding                  │      1 │ train │     0 │
│ 3  │ prescalers                         │ ModuleDict                      │     32 │ train │     0 │
│ 4  │ static_variable_selection          │ VariableSelectionNetwork        │     48 │ train │     0 │
│ 5  │ encoder_variable_selection         │ VariableSelectionNetwork        │  1.2 K │ train │     0 │
│ 6  │ decoder_variable_selection         │ VariableSelectionNetwork        │    528 │ train │     0 │
│ 7  │ static_context_variable_selection  │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 8  │ static_context_initial_hidden_lstm │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 9  │ static_context_initial_cell_lstm   │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 10 │ static_context_enrichment          │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 11 │ lstm_encoder                       │ LSTM                            │  2.2 K │ train │     0 │
│ 12 │ lstm_decoder                       │ LSTM                            │  2.2 K │ train │     0 │
│ 13 │ post_lstm_gate_encoder             │ GatedLinearUnit                 │    544 │ train │     0 │
│ 14 │ post_lstm_add_norm_encoder         │ AddNorm                         │     32 │ train │     0 │
│ 15 │ static_enrichment                  │ GatedResidualNetwork            │  1.4 K │ train │     0 │
│ 16 │ multihead_attn                     │ InterpretableMultiHeadAttention │    808 │ train │     0 │
│ 17 │ post_attn_gate_norm                │ GateAddNorm                     │    576 │ train │     0 │
│ 18 │ pos_wise_ff                        │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 19 │ pre_output_gate_norm               │ GateAddNorm                     │    576 │ train │     0 │
│ 20 │ output_layer                       │ Linear                          │    119 │ train │     0 │
└────┴────────────────────────────────────┴─────────────────────────────────┴────────┴───────┴───────┘

Trainable params: 15.7 K
Non-trainable params: 0
Total params: 15.7 K
Total estimated model params size (MB): 0
Modules in train mode: 177
Modules in eval mode: 0
Total FLOPs: 0

Output()

INFO: `Trainer.fit` stopped: `max_epochs=20` reached.
INFO:lightning.pytorch.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=20` reached.

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Training TFT -> DKI4 | so2

┏━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃    ┃ Name                               ┃ Type                            ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0  │ loss                               │ QuantileLoss                    │      0 │ train │     0 │
│ 1  │ logging_metrics                    │ ModuleList                      │      0 │ train │     0 │
│ 2  │ input_embeddings                   │ MultiEmbedding                  │      1 │ train │     0 │
│ 3  │ prescalers                         │ ModuleDict                      │     32 │ train │     0 │
│ 4  │ static_variable_selection          │ VariableSelectionNetwork        │     48 │ train │     0 │
│ 5  │ encoder_variable_selection         │ VariableSelectionNetwork        │  1.2 K │ train │     0 │
│ 6  │ decoder_variable_selection         │ VariableSelectionNetwork        │    528 │ train │     0 │
│ 7  │ static_context_variable_selection  │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 8  │ static_context_initial_hidden_lstm │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 9  │ static_context_initial_cell_lstm   │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 10 │ static_context_enrichment          │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 11 │ lstm_encoder                       │ LSTM                            │  2.2 K │ train │     0 │
│ 12 │ lstm_decoder                       │ LSTM                            │  2.2 K │ train │     0 │
│ 13 │ post_lstm_gate_encoder             │ GatedLinearUnit                 │    544 │ train │     0 │
│ 14 │ post_lstm_add_norm_encoder         │ AddNorm                         │     32 │ train │     0 │
│ 15 │ static_enrichment                  │ GatedResidualNetwork            │  1.4 K │ train │     0 │
│ 16 │ multihead_attn                     │ InterpretableMultiHeadAttention │    808 │ train │     0 │
│ 17 │ post_attn_gate_norm                │ GateAddNorm                     │    576 │ train │     0 │
│ 18 │ pos_wise_ff                        │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 19 │ pre_output_gate_norm               │ GateAddNorm                     │    576 │ train │     0 │
│ 20 │ output_layer                       │ Linear                          │    119 │ train │     0 │
└────┴────────────────────────────────────┴─────────────────────────────────┴────────┴───────┴───────┘

Trainable params: 15.7 K
Non-trainable params: 0
Total params: 15.7 K
Total estimated model params size (MB): 0
Modules in train mode: 177
Modules in eval mode: 0
Total FLOPs: 0

Output()

INFO: `Trainer.fit` stopped: `max_epochs=20` reached.
INFO:lightning.pytorch.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=20` reached.

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Training TFT -> DKI4 | co

┏━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃    ┃ Name                               ┃ Type                            ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0  │ loss                               │ QuantileLoss                    │      0 │ train │     0 │
│ 1  │ logging_metrics                    │ ModuleList                      │      0 │ train │     0 │
│ 2  │ input_embeddings                   │ MultiEmbedding                  │      1 │ train │     0 │
│ 3  │ prescalers                         │ ModuleDict                      │     32 │ train │     0 │
│ 4  │ static_variable_selection          │ VariableSelectionNetwork        │     48 │ train │     0 │
│ 5  │ encoder_variable_selection         │ VariableSelectionNetwork        │  1.2 K │ train │     0 │
│ 6  │ decoder_variable_selection         │ VariableSelectionNetwork        │    528 │ train │     0 │
│ 7  │ static_context_variable_selection  │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 8  │ static_context_initial_hidden_lstm │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 9  │ static_context_initial_cell_lstm   │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 10 │ static_context_enrichment          │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 11 │ lstm_encoder                       │ LSTM                            │  2.2 K │ train │     0 │
│ 12 │ lstm_decoder                       │ LSTM                            │  2.2 K │ train │     0 │
│ 13 │ post_lstm_gate_encoder             │ GatedLinearUnit                 │    544 │ train │     0 │
│ 14 │ post_lstm_add_norm_encoder         │ AddNorm                         │     32 │ train │     0 │
│ 15 │ static_enrichment                  │ GatedResidualNetwork            │  1.4 K │ train │     0 │
│ 16 │ multihead_attn                     │ InterpretableMultiHeadAttention │    808 │ train │     0 │
│ 17 │ post_attn_gate_norm                │ GateAddNorm                     │    576 │ train │     0 │
│ 18 │ pos_wise_ff                        │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 19 │ pre_output_gate_norm               │ GateAddNorm                     │    576 │ train │     0 │
│ 20 │ output_layer                       │ Linear                          │    119 │ train │     0 │
└────┴────────────────────────────────────┴─────────────────────────────────┴────────┴───────┴───────┘

Trainable params: 15.7 K
Non-trainable params: 0
Total params: 15.7 K
Total estimated model params size (MB): 0
Modules in train mode: 177
Modules in eval mode: 0
Total FLOPs: 0

Output()

INFO: `Trainer.fit` stopped: `max_epochs=20` reached.
INFO:lightning.pytorch.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=20` reached.

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Training TFT -> DKI4 | o3

┏━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃    ┃ Name                               ┃ Type                            ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0  │ loss                               │ QuantileLoss                    │      0 │ train │     0 │
│ 1  │ logging_metrics                    │ ModuleList                      │      0 │ train │     0 │
│ 2  │ input_embeddings                   │ MultiEmbedding                  │      1 │ train │     0 │
│ 3  │ prescalers                         │ ModuleDict                      │     32 │ train │     0 │
│ 4  │ static_variable_selection          │ VariableSelectionNetwork        │     48 │ train │     0 │
│ 5  │ encoder_variable_selection         │ VariableSelectionNetwork        │  1.2 K │ train │     0 │
│ 6  │ decoder_variable_selection         │ VariableSelectionNetwork        │    528 │ train │     0 │
│ 7  │ static_context_variable_selection  │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 8  │ static_context_initial_hidden_lstm │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 9  │ static_context_initial_cell_lstm   │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 10 │ static_context_enrichment          │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 11 │ lstm_encoder                       │ LSTM                            │  2.2 K │ train │     0 │
│ 12 │ lstm_decoder                       │ LSTM                            │  2.2 K │ train │     0 │
│ 13 │ post_lstm_gate_encoder             │ GatedLinearUnit                 │    544 │ train │     0 │
│ 14 │ post_lstm_add_norm_encoder         │ AddNorm                         │     32 │ train │     0 │
│ 15 │ static_enrichment                  │ GatedResidualNetwork            │  1.4 K │ train │     0 │
│ 16 │ multihead_attn                     │ InterpretableMultiHeadAttention │    808 │ train │     0 │
│ 17 │ post_attn_gate_norm                │ GateAddNorm                     │    576 │ train │     0 │
│ 18 │ pos_wise_ff                        │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 19 │ pre_output_gate_norm               │ GateAddNorm                     │    576 │ train │     0 │
│ 20 │ output_layer                       │ Linear                          │    119 │ train │     0 │
└────┴────────────────────────────────────┴─────────────────────────────────┴────────┴───────┴───────┘

Trainable params: 15.7 K
Non-trainable params: 0
Total params: 15.7 K
Total estimated model params size (MB): 0
Modules in train mode: 177
Modules in eval mode: 0
Total FLOPs: 0

Output()

INFO: `Trainer.fit` stopped: `max_epochs=20` reached.
INFO:lightning.pytorch.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=20` reached.

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Training TFT -> DKI4 | no2

┏━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃    ┃ Name                               ┃ Type                            ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0  │ loss                               │ QuantileLoss                    │      0 │ train │     0 │
│ 1  │ logging_metrics                    │ ModuleList                      │      0 │ train │     0 │
│ 2  │ input_embeddings                   │ MultiEmbedding                  │      1 │ train │     0 │
│ 3  │ prescalers                         │ ModuleDict                      │     32 │ train │     0 │
│ 4  │ static_variable_selection          │ VariableSelectionNetwork        │     48 │ train │     0 │
│ 5  │ encoder_variable_selection         │ VariableSelectionNetwork        │  1.2 K │ train │     0 │
│ 6  │ decoder_variable_selection         │ VariableSelectionNetwork        │    528 │ train │     0 │
│ 7  │ static_context_variable_selection  │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 8  │ static_context_initial_hidden_lstm │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 9  │ static_context_initial_cell_lstm   │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 10 │ static_context_enrichment          │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 11 │ lstm_encoder                       │ LSTM                            │  2.2 K │ train │     0 │
│ 12 │ lstm_decoder                       │ LSTM                            │  2.2 K │ train │     0 │
│ 13 │ post_lstm_gate_encoder             │ GatedLinearUnit                 │    544 │ train │     0 │
│ 14 │ post_lstm_add_norm_encoder         │ AddNorm                         │     32 │ train │     0 │
│ 15 │ static_enrichment                  │ GatedResidualNetwork            │  1.4 K │ train │     0 │
│ 16 │ multihead_attn                     │ InterpretableMultiHeadAttention │    808 │ train │     0 │
│ 17 │ post_attn_gate_norm                │ GateAddNorm                     │    576 │ train │     0 │
│ 18 │ pos_wise_ff                        │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 19 │ pre_output_gate_norm               │ GateAddNorm                     │    576 │ train │     0 │
│ 20 │ output_layer                       │ Linear                          │    119 │ train │     0 │
└────┴────────────────────────────────────┴─────────────────────────────────┴────────┴───────┴───────┘

Trainable params: 15.7 K
Non-trainable params: 0
Total params: 15.7 K
Total estimated model params size (MB): 0
Modules in train mode: 177
Modules in eval mode: 0
Total FLOPs: 0

Output()

INFO: `Trainer.fit` stopped: `max_epochs=20` reached.
INFO:lightning.pytorch.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=20` reached.

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Training TFT -> DKI5 | pm10

┏━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃    ┃ Name                               ┃ Type                            ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0  │ loss                               │ QuantileLoss                    │      0 │ train │     0 │
│ 1  │ logging_metrics                    │ ModuleList                      │      0 │ train │     0 │
│ 2  │ input_embeddings                   │ MultiEmbedding                  │      1 │ train │     0 │
│ 3  │ prescalers                         │ ModuleDict                      │     32 │ train │     0 │
│ 4  │ static_variable_selection          │ VariableSelectionNetwork        │     48 │ train │     0 │
│ 5  │ encoder_variable_selection         │ VariableSelectionNetwork        │  1.2 K │ train │     0 │
│ 6  │ decoder_variable_selection         │ VariableSelectionNetwork        │    528 │ train │     0 │
│ 7  │ static_context_variable_selection  │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 8  │ static_context_initial_hidden_lstm │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 9  │ static_context_initial_cell_lstm   │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 10 │ static_context_enrichment          │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 11 │ lstm_encoder                       │ LSTM                            │  2.2 K │ train │     0 │
│ 12 │ lstm_decoder                       │ LSTM                            │  2.2 K │ train │     0 │
│ 13 │ post_lstm_gate_encoder             │ GatedLinearUnit                 │    544 │ train │     0 │
│ 14 │ post_lstm_add_norm_encoder         │ AddNorm                         │     32 │ train │     0 │
│ 15 │ static_enrichment                  │ GatedResidualNetwork            │  1.4 K │ train │     0 │
│ 16 │ multihead_attn                     │ InterpretableMultiHeadAttention │    808 │ train │     0 │
│ 17 │ post_attn_gate_norm                │ GateAddNorm                     │    576 │ train │     0 │
│ 18 │ pos_wise_ff                        │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 19 │ pre_output_gate_norm               │ GateAddNorm                     │    576 │ train │     0 │
│ 20 │ output_layer                       │ Linear                          │    119 │ train │     0 │
└────┴────────────────────────────────────┴─────────────────────────────────┴────────┴───────┴───────┘

Trainable params: 15.7 K
Non-trainable params: 0
Total params: 15.7 K
Total estimated model params size (MB): 0
Modules in train mode: 177
Modules in eval mode: 0
Total FLOPs: 0

Output()

INFO: `Trainer.fit` stopped: `max_epochs=20` reached.
INFO:lightning.pytorch.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=20` reached.

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Training TFT -> DKI5 | so2

┏━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃    ┃ Name                               ┃ Type                            ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0  │ loss                               │ QuantileLoss                    │      0 │ train │     0 │
│ 1  │ logging_metrics                    │ ModuleList                      │      0 │ train │     0 │
│ 2  │ input_embeddings                   │ MultiEmbedding                  │      1 │ train │     0 │
│ 3  │ prescalers                         │ ModuleDict                      │     32 │ train │     0 │
│ 4  │ static_variable_selection          │ VariableSelectionNetwork        │     48 │ train │     0 │
│ 5  │ encoder_variable_selection         │ VariableSelectionNetwork        │  1.2 K │ train │     0 │
│ 6  │ decoder_variable_selection         │ VariableSelectionNetwork        │    528 │ train │     0 │
│ 7  │ static_context_variable_selection  │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 8  │ static_context_initial_hidden_lstm │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 9  │ static_context_initial_cell_lstm   │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 10 │ static_context_enrichment          │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 11 │ lstm_encoder                       │ LSTM                            │  2.2 K │ train │     0 │
│ 12 │ lstm_decoder                       │ LSTM                            │  2.2 K │ train │     0 │
│ 13 │ post_lstm_gate_encoder             │ GatedLinearUnit                 │    544 │ train │     0 │
│ 14 │ post_lstm_add_norm_encoder         │ AddNorm                         │     32 │ train │     0 │
│ 15 │ static_enrichment                  │ GatedResidualNetwork            │  1.4 K │ train │     0 │
│ 16 │ multihead_attn                     │ InterpretableMultiHeadAttention │    808 │ train │     0 │
│ 17 │ post_attn_gate_norm                │ GateAddNorm                     │    576 │ train │     0 │
│ 18 │ pos_wise_ff                        │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 19 │ pre_output_gate_norm               │ GateAddNorm                     │    576 │ train │     0 │
│ 20 │ output_layer                       │ Linear                          │    119 │ train │     0 │
└────┴────────────────────────────────────┴─────────────────────────────────┴────────┴───────┴───────┘

Trainable params: 15.7 K
Non-trainable params: 0
Total params: 15.7 K
Total estimated model params size (MB): 0
Modules in train mode: 177
Modules in eval mode: 0
Total FLOPs: 0

Output()

INFO: `Trainer.fit` stopped: `max_epochs=20` reached.
INFO:lightning.pytorch.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=20` reached.

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Training TFT -> DKI5 | co

┏━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃    ┃ Name                               ┃ Type                            ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0  │ loss                               │ QuantileLoss                    │      0 │ train │     0 │
│ 1  │ logging_metrics                    │ ModuleList                      │      0 │ train │     0 │
│ 2  │ input_embeddings                   │ MultiEmbedding                  │      1 │ train │     0 │
│ 3  │ prescalers                         │ ModuleDict                      │     32 │ train │     0 │
│ 4  │ static_variable_selection          │ VariableSelectionNetwork        │     48 │ train │     0 │
│ 5  │ encoder_variable_selection         │ VariableSelectionNetwork        │  1.2 K │ train │     0 │
│ 6  │ decoder_variable_selection         │ VariableSelectionNetwork        │    528 │ train │     0 │
│ 7  │ static_context_variable_selection  │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 8  │ static_context_initial_hidden_lstm │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 9  │ static_context_initial_cell_lstm   │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 10 │ static_context_enrichment          │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 11 │ lstm_encoder                       │ LSTM                            │  2.2 K │ train │     0 │
│ 12 │ lstm_decoder                       │ LSTM                            │  2.2 K │ train │     0 │
│ 13 │ post_lstm_gate_encoder             │ GatedLinearUnit                 │    544 │ train │     0 │
│ 14 │ post_lstm_add_norm_encoder         │ AddNorm                         │     32 │ train │     0 │
│ 15 │ static_enrichment                  │ GatedResidualNetwork            │  1.4 K │ train │     0 │
│ 16 │ multihead_attn                     │ InterpretableMultiHeadAttention │    808 │ train │     0 │
│ 17 │ post_attn_gate_norm                │ GateAddNorm                     │    576 │ train │     0 │
│ 18 │ pos_wise_ff                        │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 19 │ pre_output_gate_norm               │ GateAddNorm                     │    576 │ train │     0 │
│ 20 │ output_layer                       │ Linear                          │    119 │ train │     0 │
└────┴────────────────────────────────────┴─────────────────────────────────┴────────┴───────┴───────┘

Trainable params: 15.7 K
Non-trainable params: 0
Total params: 15.7 K
Total estimated model params size (MB): 0
Modules in train mode: 177
Modules in eval mode: 0
Total FLOPs: 0

Output()

INFO: `Trainer.fit` stopped: `max_epochs=20` reached.
INFO:lightning.pytorch.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=20` reached.

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Training TFT -> DKI5 | o3

┏━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃    ┃ Name                               ┃ Type                            ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0  │ loss                               │ QuantileLoss                    │      0 │ train │     0 │
│ 1  │ logging_metrics                    │ ModuleList                      │      0 │ train │     0 │
│ 2  │ input_embeddings                   │ MultiEmbedding                  │      1 │ train │     0 │
│ 3  │ prescalers                         │ ModuleDict                      │     32 │ train │     0 │
│ 4  │ static_variable_selection          │ VariableSelectionNetwork        │     48 │ train │     0 │
│ 5  │ encoder_variable_selection         │ VariableSelectionNetwork        │  1.2 K │ train │     0 │
│ 6  │ decoder_variable_selection         │ VariableSelectionNetwork        │    528 │ train │     0 │
│ 7  │ static_context_variable_selection  │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 8  │ static_context_initial_hidden_lstm │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 9  │ static_context_initial_cell_lstm   │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 10 │ static_context_enrichment          │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 11 │ lstm_encoder                       │ LSTM                            │  2.2 K │ train │     0 │
│ 12 │ lstm_decoder                       │ LSTM                            │  2.2 K │ train │     0 │
│ 13 │ post_lstm_gate_encoder             │ GatedLinearUnit                 │    544 │ train │     0 │
│ 14 │ post_lstm_add_norm_encoder         │ AddNorm                         │     32 │ train │     0 │
│ 15 │ static_enrichment                  │ GatedResidualNetwork            │  1.4 K │ train │     0 │
│ 16 │ multihead_attn                     │ InterpretableMultiHeadAttention │    808 │ train │     0 │
│ 17 │ post_attn_gate_norm                │ GateAddNorm                     │    576 │ train │     0 │
│ 18 │ pos_wise_ff                        │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 19 │ pre_output_gate_norm               │ GateAddNorm                     │    576 │ train │     0 │
│ 20 │ output_layer                       │ Linear                          │    119 │ train │     0 │
└────┴────────────────────────────────────┴─────────────────────────────────┴────────┴───────┴───────┘

Trainable params: 15.7 K
Non-trainable params: 0
Total params: 15.7 K
Total estimated model params size (MB): 0
Modules in train mode: 177
Modules in eval mode: 0
Total FLOPs: 0

Output()

INFO: `Trainer.fit` stopped: `max_epochs=20` reached.
INFO:lightning.pytorch.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=20` reached.

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Training TFT -> DKI5 | no2

┏━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃    ┃ Name                               ┃ Type                            ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0  │ loss                               │ QuantileLoss                    │      0 │ train │     0 │
│ 1  │ logging_metrics                    │ ModuleList                      │      0 │ train │     0 │
│ 2  │ input_embeddings                   │ MultiEmbedding                  │      1 │ train │     0 │
│ 3  │ prescalers                         │ ModuleDict                      │     32 │ train │     0 │
│ 4  │ static_variable_selection          │ VariableSelectionNetwork        │     48 │ train │     0 │
│ 5  │ encoder_variable_selection         │ VariableSelectionNetwork        │  1.2 K │ train │     0 │
│ 6  │ decoder_variable_selection         │ VariableSelectionNetwork        │    528 │ train │     0 │
│ 7  │ static_context_variable_selection  │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 8  │ static_context_initial_hidden_lstm │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 9  │ static_context_initial_cell_lstm   │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 10 │ static_context_enrichment          │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 11 │ lstm_encoder                       │ LSTM                            │  2.2 K │ train │     0 │
│ 12 │ lstm_decoder                       │ LSTM                            │  2.2 K │ train │     0 │
│ 13 │ post_lstm_gate_encoder             │ GatedLinearUnit                 │    544 │ train │     0 │
│ 14 │ post_lstm_add_norm_encoder         │ AddNorm                         │     32 │ train │     0 │
│ 15 │ static_enrichment                  │ GatedResidualNetwork            │  1.4 K │ train │     0 │
│ 16 │ multihead_attn                     │ InterpretableMultiHeadAttention │    808 │ train │     0 │
│ 17 │ post_attn_gate_norm                │ GateAddNorm                     │    576 │ train │     0 │
│ 18 │ pos_wise_ff                        │ GatedResidualNetwork            │  1.1 K │ train │     0 │
│ 19 │ pre_output_gate_norm               │ GateAddNorm                     │    576 │ train │     0 │
│ 20 │ output_layer                       │ Linear                          │    119 │ train │     0 │
└────┴────────────────────────────────────┴─────────────────────────────────┴────────┴───────┴───────┘

Trainable params: 15.7 K
Non-trainable params: 0
Total params: 15.7 K
Total estimated model params size (MB): 0
Modules in train mode: 177
Modules in eval mode: 0
Total FLOPs: 0

Output()

INFO: `Trainer.fit` stopped: `max_epochs=20` reached.
INFO:lightning.pytorch.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=20` reached.

In [ ]:
future_dates = pd.date_range(
    start="2025-09-01",
    end="2025-11-30",
    freq="D"
)

locations = ["DKI1","DKI2","DKI3","DKI4","DKI5"]

df_future = (
    pd.MultiIndex
        .from_product(
            [future_dates, locations],
            names=["tanggal", "lokasi_spku"]
        )
        .to_frame(index=False)
)

In [ ]:
df_tft.head()

,periode_data,tanggal,pm10,so2,co,o3,no2,max,critical,categori,...,no2_lag7,no2_lag30,no2_roll7_mean,no2_roll7_max,no2_roll7_std,no2_roll30_mean,no2_roll30_max,no2_roll30_std,pm10_so2_ratio,co_o3_ratio
0,201002,2010-02-06,65.0,8.0,59.0,24.0,15.0,65,PM10,SEDANG,...,17.0,14.0,13.714286,23.0,4.386125,13.800000,24.0,4.229616,8.124999,2.458333
1,201002,2010-02-08,46.0,5.0,31.0,42.0,17.0,46,PM10,BAIK,...,11.0,9.0,14.571429,23.0,4.353433,14.066667,24.0,4.168299,9.199998,0.738095
2,201002,2010-02-10,50.0,8.0,31.0,39.0,14.0,50,PM10,BAIK,...,12.0,9.0,14.857143,23.0,4.220133,14.233333,24.0,4.057206,6.249999,0.794872
3,201002,2010-02-11,47.0,5.0,27.0,26.0,14.0,47,PM10,BAIK,...,10.0,6.0,15.428571,23.0,3.690399,14.500000,24.0,3.748563,9.399998,1.038461
4,201002,2010-02-14,55.0,6.0,61.0,16.0,13.0,61,CO,SEDANG,...,13.0,8.0,15.428571,23.0,3.690399,14.666667,24.0,3.555795,9.166665,3.812500

In [ ]:
df_future = df_future.copy()
df_future["tanggal"] = pd.to_datetime(df_future["tanggal"])

all_predictions = []

for loc in locations:

    df_loc_hist = df_tft[df_tft["lokasi_spku"] == loc].copy()
    df_loc_hist = df_loc_hist.sort_values("tanggal")
    df_loc_hist["time_idx"] = np.arange(len(df_loc_hist))

    last_idx = df_loc_hist["time_idx"].max()

    df_loc_future = df_future[df_future["lokasi_spku"] == loc].copy()
    df_loc_future = df_loc_future.sort_values("tanggal")
    df_loc_future["time_idx"] = np.arange(
        last_idx + 1,
        last_idx + 1 + len(df_loc_future)
    )

    for target in targets:

        print(f"Predicting -> {loc} | {target}")

        # build df_full KHUSUS target ini
        df_full = pd.concat(
            [
                df_loc_hist[["tanggal","lokasi_spku","time_idx", target]],
                df_loc_future[["tanggal","lokasi_spku","time_idx"]]
            ],
            ignore_index=True
        )

        # isi NaN target saja
        df_full[target] = df_full[target].ffill().bfill()

        dataset = tft_datasets[(loc, target)]
        model   = tft_models[(loc, target)]

        predict_dataset = TimeSeriesDataSet.from_dataset(
            dataset,
            df_full,
            predict=True,
            stop_randomization=True
        )

        predict_loader = predict_dataset.to_dataloader(
            train=False,
            batch_size=32,
            num_workers=0
        )

        out = model.predict(
            predict_loader,
            return_x=True,
            mode="prediction"
        )

        preds = out[0]
        x     = out[1]

        preds = preds.detach().cpu().numpy()
        decoder_time_idx = x["decoder_time_idx"].detach().cpu().numpy()

        rows = []
        for i in range(preds.shape[0]):
            for j in range(preds.shape[1]):
                rows.append({
                    "lokasi_spku": loc,
                    "time_idx": int(decoder_time_idx[i, j]),
                    target: float(preds[i, j])
                })

        all_predictions.append(pd.DataFrame(rows))

from functools import reduce

df_pred_tft = pd.concat(
    all_predictions,
    ignore_index=True
)

df_pred_tft = (
    df_pred_tft
    .groupby(["lokasi_spku", "time_idx"], as_index=False)
    .first()
)

df_future_all = []

for loc in locations:

    df_loc_hist = df_tft[df_tft["lokasi_spku"] == loc].copy()
    df_loc_hist = df_loc_hist.sort_values("tanggal")
    df_loc_hist["time_idx"] = np.arange(len(df_loc_hist))

    last_idx = df_loc_hist["time_idx"].max()

    df_loc_future = df_future[df_future["lokasi_spku"] == loc].copy()
    df_loc_future = df_loc_future.sort_values("tanggal")
    df_loc_future["time_idx"] = np.arange(
        last_idx + 1,
        last_idx + 1 + len(df_loc_future)
    )

    df_future_all.append(
        df_loc_future[["lokasi_spku","tanggal","time_idx"]]
    )

df_future_index = pd.concat(df_future_all, ignore_index=True)

df_pred_tft = df_pred_tft.merge(
    df_future_index,
    on=["lokasi_spku","time_idx"],
    how="inner"
)

df_pred_tft = df_pred_tft.sort_values(
    ["lokasi_spku","tanggal"]
).reset_index(drop=True)

df_pred_tft

Predicting -> DKI1 | pm10

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO: 💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting -> DKI1 | so2

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO: 💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO: 💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.

Predicting -> DKI1 | co

INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO: 💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting -> DKI1 | o3

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO: 💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting -> DKI1 | no2
Predicting -> DKI2 | pm10

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO: 💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting -> DKI2 | so2

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO: 💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO: GPU available: True (cuda), used: True

Predicting -> DKI2 | co

INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO: 💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO: 💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting -> DKI2 | o3

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO: 💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting -> DKI2 | no2
Predicting -> DKI3 | pm10

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO: 💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting -> DKI3 | so2

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO: 💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO: 💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting -> DKI3 | co

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO: 💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting -> DKI3 | o3

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO: 💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting -> DKI3 | no2

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO: 💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.

Predicting -> DKI4 | pm10

INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO: 💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting -> DKI4 | so2

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO: 💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting -> DKI4 | co

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO: 💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting -> DKI4 | o3

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO: 💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting -> DKI4 | no2

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO: 💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting -> DKI5 | pm10

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO: 💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting -> DKI5 | so2

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO: 💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting -> DKI5 | co

INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO: 💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting -> DKI5 | o3

INFO: GPU available: True (cuda), used: True

Predicting -> DKI5 | no2

INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO: 💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

,lokasi_spku,time_idx,pm10,so2,co,o3,no2,tanggal
0,DKI1,1649,34.446556,30.497643,14.980563,11.644390,30.683018,2025-09-01
1,DKI1,1650,34.282913,31.145102,14.826178,12.233372,30.559227,2025-09-02
2,DKI1,1651,34.108559,30.924341,14.812201,12.322475,30.125814,2025-09-03
3,DKI1,1652,34.093071,30.708549,14.813911,12.337837,30.002007,2025-09-04
4,DKI1,1653,34.129555,30.490128,14.817785,12.339815,30.019424,2025-09-05
...,...,...,...,...,...,...,...,...
450,DKI5,1742,28.311096,26.376207,7.981409,35.115807,17.668945,2025-11-26
451,DKI5,1743,28.278965,26.373732,7.276232,35.119469,17.669468,2025-11-27
452,DKI5,1744,28.246468,26.371264,7.059195,35.123131,17.669991,2025-11-28
453,DKI5,1745,28.213606,26.368801,7.010227,35.126774,17.670509,2025-11-29
454,DKI5,1746,28.180374,26.366344,7.000406,35.130402,17.671028,2025-11-30

In [ ]:
df_pred_tft.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 455 entries, 0 to 454
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   lokasi_spku  455 non-null    object
 1   time_idx     455 non-null    int64
 2   pm10         455 non-null    float64
 3   so2          455 non-null    float64
 4   co           455 non-null    float64
 5   o3           455 non-null    float64
 6   no2          455 non-null    float64
 7   tanggal      455 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(5), int64(1), object(1)
memory usage: 28.6+ KB

In [ ]:
df_pred_tft.head(92)

,lokasi_spku,time_idx,pm10,so2,co,o3,no2,tanggal
0,DKI1,1649,34.446556,30.497643,14.980563,11.644390,30.683018,2025-09-01
1,DKI1,1650,34.282913,31.145102,14.826178,12.233372,30.559227,2025-09-02
2,DKI1,1651,34.108559,30.924341,14.812201,12.322475,30.125814,2025-09-03
3,DKI1,1652,34.093071,30.708549,14.813911,12.337837,30.002007,2025-09-04
4,DKI1,1653,34.129555,30.490128,14.817785,12.339815,30.019424,2025-09-05
...,...,...,...,...,...,...,...,...
87,DKI1,1736,37.837215,30.464790,15.035295,12.306824,30.259689,2025-11-27
88,DKI1,1737,37.836967,30.466705,15.037308,12.306555,30.259903,2025-11-28
89,DKI1,1738,37.836716,30.468603,15.039312,12.306288,30.260078,2025-11-29
90,DKI1,1739,37.836464,30.470486,15.041308,12.306021,30.260220,2025-11-30
91,DKI2,1897,65.879478,52.240868,13.119453,24.134483,11.699246,2025-09-01

In [ ]:
cat_cols = ['lokasi_spku', 'day_name']

In [ ]:
# Coba-Coba 12 entry cihuy

def build_forecast_features_like_train(
    df_hist,
    df_forecast,
    df_libur
):
    base_cols = ["pm10", "so2", "co", "o3", "no2"]

    # pastikan datetime
    df_hist = df_hist.copy()
    df_forecast = df_forecast.copy()

    df_hist["tanggal"] = pd.to_datetime(df_hist["tanggal"])
    df_forecast["tanggal"] = pd.to_datetime(df_forecast["tanggal"])

    # ambil hanya kolom penting dari history
    df_hist_base = df_hist[["tanggal", "lokasi_spku"] + base_cols]

    # gabungkan history + forecast
    df_all = pd.concat(
        [df_hist_base, df_forecast],
        ignore_index=True
    )

    df_all = df_all.sort_values(["lokasi_spku", "tanggal"])

    # ===============================
    # kalender
    # ===============================
    df_all = df_all.merge(
        df_libur[["tanggal", "is_holiday_nasional", "is_weekend", "day_name"]],
        on="tanggal",
        how="left"
    )

    df_all["day"] = df_all["tanggal"].dt.day
    df_all["month"] = df_all["tanggal"].dt.month
    df_all["year"] = df_all["tanggal"].dt.year
    df_all["day_of_week"] = df_all["tanggal"].dt.dayofweek

    df_all["sin_month"] = np.sin(2 * np.pi * df_all["month"] / 12)
    df_all["cos_month"] = np.cos(2 * np.pi * df_all["month"] / 12)
    df_all["sin_week"] = np.sin(2 * np.pi * df_all["day_of_week"] / 7)
    df_all["cos_week"] = np.cos(2 * np.pi * df_all["day_of_week"] / 7)

    # ===============================
    # lag & rolling (recursive style)
    # ===============================
    lag_days = [1, 7, 30]
    roll_days = [7, 30]

    df_all = df_all.sort_values(["lokasi_spku", "tanggal"])

    for col in base_cols:
        for lag in lag_days:
            df_all[f"{col}_lag{lag}"] = (
                df_all
                .groupby("lokasi_spku")[col]
                .shift(lag)
            )

        for w in roll_days:
            df_all[f"{col}_roll{w}_mean"] = (
                df_all
                .groupby("lokasi_spku")[col]
                .rolling(w)
                .mean()
                .reset_index(level=0, drop=True)
            )

            df_all[f"{col}_roll{w}_max"] = (
                df_all
                .groupby("lokasi_spku")[col]
                .rolling(w)
                .max()
                .reset_index(level=0, drop=True)
            )

            df_all[f"{col}_roll{w}_std"] = (
                df_all
                .groupby("lokasi_spku")[col]
                .rolling(w)
                .std()
                .reset_index(level=0, drop=True)
            )

    # ===============================
    # ratio
    # ===============================
    df_all["pm10_so2_ratio"] = df_all["pm10"] / (df_all["so2"] + 1e-6)
    df_all["co_o3_ratio"]   = df_all["co"]   / (df_all["o3"]  + 1e-6)

    # ===============================
    # ambil hanya baris forecast
    # ===============================
    key = set(
        zip(df_forecast["tanggal"], df_forecast["lokasi_spku"])
    )

    mask_forecast = df_all.apply(
        lambda x: (x["tanggal"], x["lokasi_spku"]) in key,
        axis=1
    )

    df_feat = df_all.loc[mask_forecast].copy()

    return df_feat

df_forecast_feat = build_forecast_features_like_train(
    df_hist=df,              # dataframe historis kamu (yang dipakai train)
    df_forecast=df_pred_tft, # output Chronos
    df_libur=df_libur
)

# cat_cols = ['lokasi_spku']
# --- 1. Filter Data & Wilayah (Sesuai Kode Lama) ---
valid_wilayah = ['DKI1', 'DKI2', 'DKI3', 'DKI4', 'DKI5']

if 'tanggal' not in df_forecast_feat.columns and 'date' in df_forecast_feat.columns:
    df_forecast_feat['tanggal'] = df_forecast_feat['date'] # Penyesuaian nama kolom jika perlu

df_forecast_feat['tanggal'] = pd.to_datetime(df_forecast_feat['tanggal'])
df_forecast_clean = df_forecast_feat[df_forecast_feat['lokasi_spku'].isin(valid_wilayah)].copy()

# --- FIX: Tambahkan day_name karena hilang saat forecasting ---
df_forecast_clean['day_name'] = df_forecast_clean['tanggal'].dt.day_name()

print(f"Jumlah data yang akan diprediksi: {len(df_forecast_clean)}")


df_forecast_enc = df_forecast_clean.copy()

# Pastikan urutan kolom sesuai dengan encoder
df_forecast_enc[cat_cols] = encoder.transform(df_forecast_clean[cat_cols])

feature_columns = X_train.columns
X_pred = df_forecast_enc[feature_columns]

y_pred_numeric = final_xgb_model.predict(X_pred)

df_forecast_clean['categori'] = le.inverse_transform(y_pred_numeric)

# Buat ID: YYYY-MM-DD_WILAYAH
df_forecast_clean['id'] = (
    df_forecast_clean['tanggal'].dt.strftime('%Y-%m-%d')
    + '_'
    + df_forecast_clean['lokasi_spku']
)

# --- 5. Finalisasi & Save ---
df_submission = df_forecast_clean[['id', 'categori']].sort_values('id')

# Simpan CSV
filename = 'submission_tft_2.csv'
df_submission.to_csv(filename, index=False)

print(f"Berhasil menyimpan file: {filename}")
print("\nContoh 15 baris pertama:")
print(df_submission.head(15))

Jumlah data yang akan diprediksi: 455
Berhasil menyimpan file: submission_tft_2.csv

Contoh 15 baris pertama:
                   id categori
1649  2025-09-01_DKI1   SEDANG
3637  2025-09-01_DKI2   SEDANG
5330  2025-09-01_DKI3   SEDANG
7275  2025-09-01_DKI4   SEDANG
9022  2025-09-01_DKI5     BAIK
1650  2025-09-02_DKI1   SEDANG
3638  2025-09-02_DKI2   SEDANG
5331  2025-09-02_DKI3   SEDANG
7276  2025-09-02_DKI4   SEDANG
9023  2025-09-02_DKI5     BAIK
1651  2025-09-03_DKI1   SEDANG
3639  2025-09-03_DKI2   SEDANG
5332  2025-09-03_DKI3   SEDANG
7277  2025-09-03_DKI4   SEDANG
9024  2025-09-03_DKI5     BAIK

In [ ]:
df_submission['categori'].value_counts()

categori
SEDANG         276
BAIK            91
TIDAK SEHAT     88
Name: count, dtype: int64

In [ ]:
df_submission.head(50)

                   id     categori
1649  2025-09-01_DKI1       SEDANG
3637  2025-09-01_DKI2       SEDANG
5330  2025-09-01_DKI3       SEDANG
7275  2025-09-01_DKI4       SEDANG
9022  2025-09-01_DKI5         BAIK
1650  2025-09-02_DKI1       SEDANG
3638  2025-09-02_DKI2       SEDANG
5331  2025-09-02_DKI3       SEDANG
7276  2025-09-02_DKI4       SEDANG
9023  2025-09-02_DKI5         BAIK
1651  2025-09-03_DKI1       SEDANG
3639  2025-09-03_DKI2       SEDANG
5332  2025-09-03_DKI3       SEDANG
7277  2025-09-03_DKI4       SEDANG
9024  2025-09-03_DKI5         BAIK
1652  2025-09-04_DKI1       SEDANG
3640  2025-09-04_DKI2       SEDANG
5333  2025-09-04_DKI3       SEDANG
7278  2025-09-04_DKI4  TIDAK SEHAT
9025  2025-09-04_DKI5         BAIK
1653  2025-09-05_DKI1       SEDANG
3641  2025-09-05_DKI2       SEDANG
5334  2025-09-05_DKI3       SEDANG
7279  2025-09-05_DKI4  TIDAK SEHAT
9026  2025-09-05_DKI5         BAIK
1654  2025-09-06_DKI1       SEDANG
3642  2025-09-06_DKI2       SEDANG
5335  2025-09-06_DKI3       SEDANG
7280  2025-09-06_DKI4  TIDAK SEHAT
9027  2025-09-06_DKI5         BAIK
1655  2025-09-07_DKI1       SEDANG
3643  2025-09-07_DKI2       SEDANG
5336  2025-09-07_DKI3       SEDANG
7281  2025-09-07_DKI4  TIDAK SEHAT
9028  2025-09-07_DKI5         BAIK
1656  2025-09-08_DKI1       SEDANG
3644  2025-09-08_DKI2       SEDANG
5337  2025-09-08_DKI3       SEDANG
7282  2025-09-08_DKI4  TIDAK SEHAT
9029  2025-09-08_DKI5         BAIK
1657  2025-09-09_DKI1       SEDANG
3645  2025-09-09_DKI2       SEDANG
5338  2025-09-09_DKI3       SEDANG
7283  2025-09-09_DKI4  TIDAK SEHAT
9030  2025-09-09_DKI5         BAIK
1658  2025-09-10_DKI1       SEDANG
3646  2025-09-10_DKI2       SEDANG
5339  2025-09-10_DKI3       SEDANG
7284  2025-09-10_DKI4  TIDAK SEHAT
9031  2025-09-10_DKI5         BAIK